import { byLevel } from './classes-martial';
import { STANDARD_ASI, type ClassChoice, type ClassDef } from './classes-types';

const FULL_PREPARED = [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 16, 17, 17, 18, 18, 19, 20, 21, 22];
const HALF_PREPARED = [2, 3, 4, 5, 6, 6, 7, 7, 9, 9, 10, 10, 11, 11, 12, 12, 14, 14, 15, 15];
const cantrips = (base: number) => byLevel([[1, base], [4, base + 1], [10, base + 2]]);
const EPIC = { level: 19, name: 'Dono epico', description: 'Ottieni un talento Dono epico.' };

export const BARD: ClassDef = {
  id: 'bard',
  name: 'Bardo',
  description: 'Artista ispiratore la cui magia risuona nella musica e nella parola.',
  hitDie: 8,
  primary: ['cha'],
  saves: ['dex', 'cha'],
  skillChoices: 3,
  skillList: null,
  armor: ['light'],
  martial: false,
  tools: 'Tre strumenti musicali',
  spellcasting: { ability: 'cha', type: 'full', cantrips: cantrips(2), prepared: FULL_PREPARED },
  expertise: [
    { level: 2, count: 2 },
    { level: 9, count: 2 },
  ],
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Collegio bardico',
  resources: [
    {
      id: 'bardicInspiration',
      name: 'Ispirazione bardica',
      level: 1,
      recharge: 'long',
      shortFrom: 5,
      max: (_l, m) => Math.max(1, m.cha),
      die: (l) => (l >= 15 ? 'd12' : l >= 10 ? 'd10' : l >= 5 ? 'd8' : 'd6'),
    },
  ],
  features: [
    { level: 1, name: 'Ispirazione bardica', description: 'Azione bonus: una creatura entro 18 m ottiene un dado di ispirazione da aggiungere a una prova d20 fallita entro un’ora. Usi pari al mod. di Carisma.' },
    { level: 1, name: 'Incantesimi', description: 'Lanci incantesimi da bardo usando il Carisma; puoi usare uno strumento musicale come focus.' },
    { level: 2, name: 'Maestria', description: 'Raddoppi la competenza in due abilità (altre due al 9°).' },
    { level: 2, name: 'Factotum', description: 'Aggiungi metà competenza alle prove di abilità in cui non hai competenza.' },
    { level: 5, name: 'Fonte di ispirazione', description: 'Recuperi l’Ispirazione bardica con un riposo breve; puoi spendere uno slot per recuperarne un uso.' },
    { level: 7, name: 'Controfascino', description: 'Reazione: una creatura entro 9 m ripete con Vantaggio un TS contro Affascinato o Spaventato.' },
    { level: 10, name: 'Segreti magici', description: 'Puoi preparare incantesimi dalle liste di bardo, chierico, druido e mago.' },
    { level: 18, name: 'Ispirazione superiore', description: 'Tirando l’iniziativa, se hai meno di 2 usi di Ispirazione bardica risali a 2.' },
    EPIC,
    { level: 20, name: 'Parole di creazione', description: 'Hai sempre preparati Parola divina e Parola del potere uccidere, e puoi colpire una seconda creatura entro 3 m.' },
  ],
  subclasses: [
    {
      id: 'lore',
      name: 'Collegio della sapienza',
      description: 'Collezionisti di segreti e di magia.',
      features: [
        { level: 3, name: 'Competenze bonus', description: 'Competenza in tre abilità a scelta.' },
        { level: 3, name: 'Parole taglienti', description: 'Reazione: spendi un’Ispirazione bardica per sottrarre il dado a un tiro per colpire, una prova o un tiro di danno di una creatura entro 18 m.' },
        { level: 6, name: 'Scoperte magiche', description: 'Due incantesimi a scelta dalle liste di chierico, druido o mago, sempre preparati.' },
        { level: 14, name: 'Abilità impareggiabile', description: 'Quando fallisci una prova o un tiro per colpire, puoi aggiungere un dado di Ispirazione bardica; se fallisci ancora non lo spendi.' },
      ],
    },
  ],
  equipment: [
    { label: 'Armatura di cuoio, 2 pugnali, uno strumento musicale, dotazione da intrattenitore e 19 mo', kit: [{ item: 'leather' }, { item: 'dagger', qty: 2 }, { item: 'musicalInstrument' }, { item: 'entertainersPack' }], gold: 19 },
    { label: '90 mo', kit: [], gold: 90 },
  ],
};

export const CLERIC: ClassDef = {
  id: 'cleric',
  name: 'Chierico',
  description: 'Campione sacerdotale che incanala il potere divino.',
  hitDie: 8,
  primary: ['wis'],
  saves: ['wis', 'cha'],
  skillChoices: 2,
  skillList: ['history', 'insight', 'medicine', 'persuasion', 'religion'],
  armor: ['light', 'medium', 'shield'],
  martial: false,
  spellcasting: { ability: 'wis', type: 'full', cantrips: cantrips(3), prepared: FULL_PREPARED },
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Dominio divino',
  choices: [
    {
      key: 'divineOrder',
      label: 'Ordine divino',
      level: 1,
      options: [
        { id: 'protector', name: 'Protettore', description: 'Addestramento con armi da guerra e armature pesanti.' },
        { id: 'thaumaturge', name: 'Taumaturgo', description: 'Un trucchetto extra e + Sag alle prove di Arcano e Religione.' },
      ],
    },
    {
      key: 'blessedStrikes',
      label: 'Colpi benedetti',
      level: 7,
      options: [
        { id: 'divineStrike', name: 'Colpo divino', description: 'Una volta per turno, +1d8 danni necrotici o radiosi con un’arma (2d8 al 14°).' },
        { id: 'potentSpellcasting', name: 'Incantesimi potenti', description: '+ Sag ai danni dei trucchetti (e PF temporanei agli alleati al 14°).' },
      ],
    },
  ],
  resources: [
    { id: 'channelDivinity', name: 'Incanalare divinità', level: 2, recharge: 'long', shortRestOne: true, max: (l) => (l >= 18 ? 4 : l >= 6 ? 3 : 2) },
    { id: 'divineIntervention', name: 'Intervento divino', level: 10, recharge: 'long', max: () => 1 },
  ],
  features: [
    { level: 1, name: 'Incantesimi', description: 'Lanci incantesimi da chierico usando la Saggezza; il simbolo sacro è il tuo focus.' },
    { level: 1, name: 'Ordine divino', description: 'Protettore (armi da guerra e armature pesanti) o Taumaturgo (trucchetto extra, bonus ad Arcano e Religione).' },
    { level: 2, name: 'Incanalare divinità', description: 'Scintilla divina (cura o danno di 1d8 + Sag, 2d8 al 7°, 3d8 al 13°, 4d8 al 18°) e Scacciare non morti. Due usi (3 al 6°, 4 al 18°); un uso torna con riposo breve.' },
    { level: 5, name: 'Distruggere non morti', description: 'Con Scacciare non morti infliggi danni radiosi pari a tanti d8 quanto il mod. di Saggezza.' },
    { level: 7, name: 'Colpi benedetti', description: 'Colpo divino oppure Incantesimi potenti.' },
    { level: 10, name: 'Intervento divino', description: 'Con un’azione Magia lanci senza slot un incantesimo da chierico di 5° livello o inferiore. Una volta per riposo lungo.' },
    { level: 14, name: 'Colpi benedetti migliorati', description: 'Colpo divino a 2d8, oppure gli Incantesimi potenti danno anche PF temporanei.' },
    EPIC,
    { level: 20, name: 'Intervento divino superiore', description: 'Con l’Intervento divino puoi lanciare Desiderio (poi 2d4 riposi lunghi per riusarlo).' },
  ],
  subclasses: [
    {
      id: 'life',
      name: 'Dominio della vita',
      description: 'L’energia positiva che sostiene ogni vita.',
      spells: [
        { level: 3, spells: ['aid', 'bless', 'cureWounds', 'lesserRestoration'] },
        { level: 5, spells: ['massHealingWord', 'revivify'] },
        { level: 7, spells: ['auraOfLife', 'deathWard'] },
        { level: 9, spells: ['greaterRestoration', 'massCureWounds'] },
      ],
      features: [
        { level: 3, name: 'Discepolo della vita', description: 'Gli incantesimi che curano recuperano PF extra pari a 2 + livello dell’incantesimo.' },
        { level: 3, name: 'Preservare la vita', description: 'Incanalare divinità: ripartisci PF pari a 5 × livello da chierico tra creature entro 9 m (fino a metà del loro massimo).' },
        { level: 6, name: 'Guaritore benedetto', description: 'Quando curi un altro con uno slot, recuperi 2 + livello dello slot PF.' },
        { level: 17, name: 'Guarigione suprema', description: 'I dadi di cura dei tuoi incantesimi danno sempre il massimo.' },
      ],
    },
  ],
  equipment: [
    { label: 'Giaco di maglia, scudo, mazza, simbolo sacro, dotazione da sacerdote e 7 mo', kit: [{ item: 'chainShirt' }, { item: 'shield' }, { item: 'mace' }, { item: 'holySymbol' }, { item: 'priestsPack' }], gold: 7 },
    { label: '110 mo', kit: [], gold: 110 },
  ],
};

export const DRUID: ClassDef = {
  id: 'druid',
  name: 'Druido',
  description: 'Sacerdote della natura che attinge alla magia primordiale.',
  hitDie: 8,
  primary: ['wis'],
  saves: ['int', 'wis'],
  skillChoices: 2,
  skillList: ['arcana', 'animalHandling', 'insight', 'medicine', 'nature', 'perception', 'religion', 'survival'],
  armor: ['light', 'shield'],
  martial: false,
  tools: 'Borsa da erborista',
  spellcasting: { ability: 'wis', type: 'full', cantrips: cantrips(2), prepared: FULL_PREPARED },
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Circolo druidico',
  choices: [
    {
      key: 'primalOrder',
      label: 'Ordine primordiale',
      level: 1,
      options: [
        { id: 'magician', name: 'Mago', description: 'Un trucchetto extra e + Sag alle prove di Arcano e Natura.' },
        { id: 'warden', name: 'Guardiano', description: 'Addestramento con armi da guerra e armature medie.' },
      ],
    },
    {
      key: 'elementalFury',
      label: 'Furia elementale',
      level: 7,
      options: [
        { id: 'potentSpellcasting', name: 'Incantesimi potenti', description: '+ Sag ai danni dei trucchetti.' },
        { id: 'primalStrike', name: 'Colpo primordiale', description: 'Una volta per turno, +1d8 danni da freddo, fuoco, fulmine o tuono con un attacco (2d8 al 15°).' },
      ],
    },
  ],
  resources: [{ id: 'wildShape', name: 'Forma selvatica', level: 2, recharge: 'long', shortRestOne: true, max: (l) => (l >= 17 ? 4 : l >= 6 ? 3 : 2) }],
  features: [
    { level: 1, name: 'Incantesimi', description: 'Lanci incantesimi da druido usando la Saggezza; il focus druidico è il tuo strumento.' },
    { level: 1, name: 'Druidico', description: 'Conosci la lingua segreta dei druidi e hai sempre preparato Parlare con gli animali.' },
    { level: 1, name: 'Ordine primordiale', description: 'Mago (trucchetto extra) o Guardiano (armi da guerra e armature medie).' },
    { level: 2, name: 'Forma selvatica', description: 'Azione bonus: assumi la forma di una bestia conosciuta (GS 1/4, 1/2 al 4°, 1 all’8°) per metà del livello in ore. Due usi (3 al 6°, 4 al 17°).' },
    { level: 2, name: 'Compagno selvatico', description: 'Spendi uno slot o un uso di Forma selvatica per lanciare Trovare famiglio senza componenti materiali.' },
    { level: 5, name: 'Risorgere selvatico', description: 'Se non hai usi di Forma selvatica puoi spendere uno slot per recuperarne uno, o un uso per recuperare uno slot di 1° livello.' },
    { level: 7, name: 'Furia elementale', description: 'Incantesimi potenti oppure Colpo primordiale.' },
    { level: 15, name: 'Furia elementale migliorata', description: 'I trucchetti a distanza guadagnano 90 m di gittata, oppure il Colpo primordiale sale a 2d8.' },
    { level: 18, name: 'Incantesimi bestiali', description: 'Puoi lanciare incantesimi in Forma selvatica.' },
    EPIC,
    { level: 20, name: 'Arcidruido', description: 'Tirando l’iniziativa recuperi un uso di Forma selvatica; puoi convertire usi di Forma selvatica in slot.' },
  ],
  subclasses: [
    {
      id: 'land',
      name: 'Circolo della terra',
      description: 'Custodi della magia antica della terra.',
      choices: [
        {
          key: 'landType',
          label: 'Terra del circolo',
          level: 3,
          options: [
            { id: 'arid', name: 'Arida', description: 'Sfocatura, Mani brucianti, Dardo di fuoco; Palla di fuoco; Avvizzire; Muro di pietra.' },
            { id: 'polar', name: 'Polare', description: 'Nube di nebbia, Blocca persone, Raggio di gelo; Tempesta di nevischio; Tempesta di ghiaccio; Cono di freddo.' },
            { id: 'temperate', name: 'Temperata', description: 'Passo velato, Stretta folgorante, Sonno; Fulmine; Libertà di movimento; Passo arboreo.' },
            { id: 'tropical', name: 'Tropicale', description: 'Fiotto acido, Raggio di infermità, Ragnatela; Nube maleodorante; Metamorfosi; Piaga di insetti.' },
          ],
        },
      ],
      features: [
        { level: 3, name: 'Incantesimi del circolo', description: 'Incantesimi sempre preparati legati alla terra scelta (cambiabile a ogni riposo lungo).' },
        { level: 3, name: 'Aiuto della terra', description: 'Spendi un uso di Forma selvatica: sfera di 3 m entro 18 m, 2d6 danni necrotici (TS Cos) e cura di 2d6 a una creatura (sale al 10° e al 14°).' },
        { level: 6, name: 'Recupero naturale', description: 'Una volta per riposo lungo lanci un incantesimo del circolo senza slot, e con un riposo breve recuperi slot fino a metà del livello.' },
        { level: 10, name: 'Protezione della natura', description: 'Immunità ad Avvelenato e resistenza al danno della tua terra.' },
        { level: 14, name: 'Santuario della natura', description: 'Spendi un uso di Forma selvatica per creare un cubo di 4,5 m di alberi spettrali che dà mezza copertura agli alleati.' },
      ],
    },
  ],
  equipment: [
    {
      label: 'Armatura di cuoio, scudo, falcetto, focus druidico, dotazione da esploratore, borsa da erborista e 9 mo',
      kit: [{ item: 'leather' }, { item: 'shield' }, { item: 'sickle' }, { item: 'druidicFocus' }, { item: 'explorersPack' }, { item: 'herbalismKit' }],
      gold: 9,
    },
    { label: '50 mo', kit: [], gold: 50 },
  ],
};

export const PALADIN: ClassDef = {
  id: 'paladin',
  name: 'Paladino',
  description: 'Guerriero devoto legato a un giuramento sacro.',
  hitDie: 10,
  primary: ['str', 'cha'],
  saves: ['wis', 'cha'],
  skillChoices: 2,
  skillList: ['athletics', 'insight', 'intimidation', 'medicine', 'persuasion', 'religion'],
  armor: ['light', 'medium', 'heavy', 'shield'],
  martial: true,
  spellcasting: { ability: 'cha', type: 'half', prepared: HALF_PREPARED },
  masteries: byLevel([[1, 2]]),
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Giuramento sacro',
  choices: [{ key: 'fightingStyle', label: 'Stile di combattimento', level: 2, options: [] }],
  resources: [
    { id: 'layOnHands', name: 'Imposizione delle mani', level: 1, recharge: 'long', max: (l) => 5 * l, die: () => 'PF' },
    { id: 'paladinsSmite', name: 'Punizione gratuita', level: 2, recharge: 'long', max: () => 1 },
    { id: 'channelDivinity', name: 'Incanalare divinità', level: 3, recharge: 'long', shortRestOne: true, max: (l) => (l >= 11 ? 3 : 2) },
  ],
  features: [
    { level: 1, name: 'Imposizione delle mani', description: 'Azione bonus: riserva di 5 × livello PF per curare, o 5 PF per rimuovere Avvelenato.' },
    { level: 1, name: 'Incantesimi', description: 'Lanci incantesimi da paladino usando il Carisma.' },
    { level: 1, name: 'Maestria nelle armi', description: 'Usi la maestria di 2 tipi di armi.' },
    { level: 2, name: 'Stile di combattimento', description: 'Un talento Stile di combattimento (o il Guerriero benedetto: due trucchetti da chierico).' },
    { level: 2, name: 'Punizione del paladino', description: 'Hai sempre preparata Punizione divina e puoi lanciarla una volta per riposo lungo senza slot.' },
    { level: 3, name: 'Incanalare divinità', description: 'Percezione divina e le opzioni del giuramento. Due usi (3 all’11°); uno torna con riposo breve.' },
    { level: 5, name: 'Attacco extra', description: 'Attacchi due volte con l’azione di Attacco.' },
    { level: 5, name: 'Destriero fedele', description: 'Hai sempre preparato Trovare destriero e puoi lanciarlo una volta per riposo lungo senza slot.' },
    { level: 6, name: 'Aura di protezione', description: 'Tu e gli alleati entro 3 m aggiungete il tuo mod. di Carisma ai TS.' },
    { level: 9, name: 'Abiurare nemici', description: 'Incanalare divinità: creature scelte entro 18 m fanno TS su Saggezza o sono Spaventate.' },
    { level: 10, name: 'Aura di coraggio', description: 'Tu e gli alleati nell’aura siete immuni a Spaventato.' },
    { level: 11, name: 'Colpi radiosi', description: 'Gli attacchi con armi infliggono +1d8 danni radiosi.' },
    { level: 14, name: 'Tocco purificatore', description: 'Con Imposizione delle mani puoi rimuovere condizioni spendendo 5 PF ciascuna.' },
    { level: 18, name: 'Espansione dell’aura', description: 'Le aure arrivano a 9 m.' },
    EPIC,
  ],
  subclasses: [
    {
      id: 'devotion',
      name: 'Giuramento di devozione',
      description: 'Gli ideali del cavaliere: onore, lealtà, purezza.',
      spells: [
        { level: 3, spells: ['protectionFromEvilAndGood', 'shieldOfFaith'] },
        { level: 5, spells: ['aid', 'zoneOfTruth'] },
        { level: 9, spells: ['beaconOfHope', 'dispelMagic'] },
        { level: 13, spells: ['freedomOfMovement', 'guardianOfFaith'] },
        { level: 17, spells: ['commune', 'flameStrike'] },
      ],
      features: [
        { level: 3, name: 'Arma sacra', description: 'Incanalare divinità: per 10 minuti aggiungi il Carisma ai tiri per colpire con un’arma che emette luce e infligge danni radiosi.' },
        { level: 7, name: 'Aura di devozione', description: 'Tu e gli alleati nell’aura siete immuni ad Affascinato.' },
        { level: 15, name: 'Punizione protettiva', description: 'Quando lanci Punizione divina, tu e gli alleati nell’aura avete mezza copertura fino al tuo prossimo turno.' },
        { level: 20, name: 'Nimbo sacro', description: 'Azione bonus per 10 minuti: luce solare, Vantaggio ai TS contro immondi e non morti, danni radiosi ai nemici nell’aura.' },
      ],
    },
  ],
  equipment: [
    {
      label: 'Cotta di maglia, scudo, spada lunga, 6 giavellotti, simbolo sacro, dotazione da sacerdote e 9 mo',
      kit: [{ item: 'chainMail' }, { item: 'shield' }, { item: 'longsword' }, { item: 'javelin', qty: 6 }, { item: 'holySymbol' }, { item: 'priestsPack' }],
      gold: 9,
    },
    { label: '150 mo', kit: [], gold: 150 },
  ],
};

export const RANGER: ClassDef = {
  id: 'ranger',
  name: 'Ranger',
  description: 'Vagabondo delle terre selvagge e cacciatore implacabile.',
  hitDie: 10,
  primary: ['dex', 'wis'],
  saves: ['str', 'dex'],
  skillChoices: 3,
  skillList: ['animalHandling', 'athletics', 'insight', 'investigation', 'nature', 'perception', 'stealth', 'survival'],
  armor: ['light', 'medium', 'shield'],
  martial: true,
  spellcasting: { ability: 'wis', type: 'half', prepared: HALF_PREPARED },
  masteries: byLevel([[1, 2]]),
  expertise: [
    { level: 2, count: 1 },
    { level: 9, count: 2 },
  ],
  speedBonus: (l) => (l >= 6 ? 3 : 0),
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Archetipo del ranger',
  choices: [{ key: 'fightingStyle', label: 'Stile di combattimento', level: 2, options: [] }],
  resources: [{ id: 'favoredEnemy', name: 'Marchio del cacciatore gratuito', level: 1, recharge: 'long', max: (l) => (l >= 17 ? 6 : l >= 13 ? 5 : l >= 9 ? 4 : l >= 5 ? 3 : 2) }],
  features: [
    { level: 1, name: 'Incantesimi', description: 'Lanci incantesimi da ranger usando la Saggezza.' },
    { level: 1, name: 'Nemico prescelto', description: 'Hai sempre preparato Marchio del cacciatore e puoi lanciarlo senza slot (2 volte per riposo lungo, di più salendo di livello).' },
    { level: 1, name: 'Maestria nelle armi', description: 'Usi la maestria di 2 tipi di armi.' },
    { level: 2, name: 'Esploratore abile', description: 'Maestria in un’abilità in cui hai competenza e due lingue.' },
    { level: 2, name: 'Stile di combattimento', description: 'Un talento Stile di combattimento (o il Guerriero druidico: due trucchetti da druido).' },
    { level: 5, name: 'Attacco extra', description: 'Attacchi due volte con l’azione di Attacco.' },
    { level: 6, name: 'Vagabondo', description: '+3 m di Velocità senza armatura pesante; Velocità di nuotare e scalare pari alla Velocità.' },
    { level: 9, name: 'Maestria', description: 'Maestria in due abilità.' },
    { level: 10, name: 'Instancabile', description: 'Magia: PF temporanei pari a 1d8 + Sag (usi pari al mod.); un riposo breve riduce l’Indebolimento di 1.' },
    { level: 13, name: 'Cacciatore implacabile', description: 'I danni non interrompono la concentrazione su Marchio del cacciatore.' },
    { level: 14, name: 'Velo della natura', description: 'Azione bonus: diventi Invisibile fino alla fine del tuo prossimo turno (usi pari al mod. di Saggezza).' },
    { level: 17, name: 'Cacciatore preciso', description: 'Vantaggio agli attacchi contro la creatura marchiata.' },
    { level: 18, name: 'Sensi ferini', description: 'Vista cieca entro 9 m.' },
    EPIC,
    { level: 20, name: 'Uccisore di nemici', description: 'Il dado del Marchio del cacciatore diventa un d10.' },
  ],
  subclasses: [
    {
      id: 'hunter',
      name: 'Cacciatore',
      description: 'Specialista nell’abbattere prede pericolose.',
      choices: [
        {
          key: 'huntersPrey',
          label: 'Preda del cacciatore',
          level: 3,
          options: [
            { id: 'colossusSlayer', name: 'Uccisore di colossi', description: 'Una volta per turno +1d8 danni a una creatura ferita.' },
            { id: 'hordeBreaker', name: 'Distruttore di orde', description: 'Una volta per turno un attacco extra contro una seconda creatura entro 1,5 m dal bersaglio.' },
          ],
        },
        {
          key: 'defensiveTactics',
          label: 'Tattiche difensive',
          level: 7,
          options: [
            { id: 'escapeTheHorde', name: 'Sfuggire all’orda', description: 'Gli attacchi di opportunità contro di te hanno Svantaggio.' },
            { id: 'multiattackDefense', name: 'Difesa dai multiattacchi', description: 'Dopo che una creatura ti colpisce, i suoi altri attacchi nel turno hanno Svantaggio.' },
          ],
        },
      ],
      features: [
        { level: 3, name: 'Conoscenza del cacciatore', description: 'Mentre una creatura è marchiata conosci le sue immunità, resistenze e vulnerabilità.' },
        { level: 3, name: 'Preda del cacciatore', description: 'Uccisore di colossi o Distruttore di orde (cambiabile a ogni riposo).' },
        { level: 7, name: 'Tattiche difensive', description: 'Sfuggire all’orda o Difesa dai multiattacchi.' },
        { level: 11, name: 'Preda superiore', description: 'Una volta per turno il danno del Marchio del cacciatore colpisce anche una seconda creatura entro 9 m.' },
        { level: 15, name: 'Difesa superiore del cacciatore', description: 'Reazione quando subisci danni: resistenza a quel tipo di danno fino alla fine del turno.' },
      ],
    },
  ],
  equipment: [
    {
      label: 'Cuoio borchiato, scimitarra, spada corta, arco lungo, 20 frecce, faretra, focus druidico, dotazione da esploratore e 7 mo',
      kit: [{ item: 'studded' }, { item: 'scimitar' }, { item: 'shortsword' }, { item: 'longbow' }, { item: 'arrows' }, { item: 'quiver' }, { item: 'druidicFocus' }, { item: 'explorersPack' }],
      gold: 7,
    },
    { label: '150 mo', kit: [], gold: 150 },
  ],
};

const METAMAGIC: ClassChoice = {
  key: 'metamagic',
  label: 'Metamagia',
  level: 2,
  count: byLevel([[2, 2], [10, 4], [17, 6]]),
  options: [
    { id: 'careful', name: 'Incantesimo accurato', description: '1 punto: creature scelte superano automaticamente il TS del tuo incantesimo e non subiscono danni se ne subirebbero metà.' },
    { id: 'distant', name: 'Incantesimo distante', description: '1 punto: raddoppi la gittata (o portata 9 m per quelli a contatto).' },
    { id: 'empowered', name: 'Incantesimo potenziato', description: '1 punto: ritiri dadi di danno fino al mod. di Carisma.' },
    { id: 'extended', name: 'Incantesimo esteso', description: '1 punto: raddoppi la durata (fino a 24 ore) e hai Vantaggio ai TS di concentrazione.' },
    { id: 'heightened', name: 'Incantesimo intensificato', description: '2 punti: un bersaglio ha Svantaggio al TS contro l’incantesimo.' },
    { id: 'quickened', name: 'Incantesimo rapido', description: '2 punti: lanci come azione bonus un incantesimo che richiede un’azione.' },
    { id: 'seeking', name: 'Incantesimo cercatore', description: '1 punto: ritiri un tiro per colpire mancato.' },
    { id: 'subtle', name: 'Incantesimo sottile', description: '1 punto: niente componenti verbali, somatiche o materiali senza costo.' },
    { id: 'transmuted', name: 'Incantesimo trasmutato', description: '1 punto: cambi il tipo di danno tra acido, freddo, fuoco, fulmine, veleno e tuono.' },
    { id: 'twinned', name: 'Incantesimo gemello', description: 'Punti pari al livello dell’incantesimo: un secondo bersaglio per incantesimi a bersaglio singolo che salgono di livello.' },
  ],
};

export const SORCERER: ClassDef = {
  id: 'sorcerer',
  name: 'Stregone',
  description: 'Incantatore con una magia innata nel sangue.',
  hitDie: 6,
  primary: ['cha'],
  saves: ['con', 'cha'],
  skillChoices: 2,
  skillList: ['arcana', 'deception', 'insight', 'intimidation', 'persuasion', 'religion'],
  armor: [],
  martial: false,
  spellcasting: { ability: 'cha', type: 'full', cantrips: cantrips(4), prepared: [2, 4, 6, 7, 9, 10, 11, 12, 14, 15, 16, 16, 17, 17, 18, 18, 19, 20, 21, 22] },
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Origine stregonesca',
  choices: [METAMAGIC],
  resources: [
    { id: 'innateSorcery', name: 'Stregoneria innata', level: 1, recharge: 'long', max: () => 2 },
    { id: 'sorceryPoints', name: 'Punti stregoneria', level: 2, recharge: 'long', max: (l) => l },
  ],
  features: [
    { level: 1, name: 'Incantesimi', description: 'Lanci incantesimi da stregone usando il Carisma.' },
    { level: 1, name: 'Stregoneria innata', description: 'Azione bonus per 1 minuto: +1 alla CD dei tuoi incantesimi e Vantaggio ai tiri per colpire con incantesimi. Due volte per riposo lungo.' },
    { level: 2, name: 'Fonte di magia', description: 'Punti stregoneria pari al livello: convertili in slot o viceversa.' },
    { level: 2, name: 'Metamagia', description: 'Due opzioni di metamagia (quattro al 10°, sei al 17°).' },
    { level: 5, name: 'Ripristino stregonesco', description: 'Con un riposo breve recuperi punti stregoneria pari a metà del livello (una volta per riposo lungo).' },
    { level: 7, name: 'Stregoneria incarnata', description: 'Se non hai usi di Stregoneria innata puoi attivarla con 2 punti; mentre è attiva puoi usare due opzioni di metamagia per incantesimo.' },
    EPIC,
    { level: 20, name: 'Apoteosi arcana', description: 'Mentre la Stregoneria innata è attiva, una metamagia per turno non costa punti.' },
  ],
  subclasses: [
    {
      id: 'draconic',
      name: 'Stregoneria draconica',
      description: 'Il sangue dei draghi scorre nelle tue vene.',
      spells: [
        { level: 3, spells: ['alterSelf', 'chromaticOrb', 'command', 'dragonsBreath'] },
        { level: 5, spells: ['fear', 'fly'] },
        { level: 7, spells: ['arcaneEye', 'charmMonster'] },
        { level: 9, spells: ['legendLore', 'summonDragon'] },
      ],
      features: [
        { level: 3, name: 'Resilienza draconica', description: 'Il massimo dei PF aumenta di 3 e poi di 1 per livello; senza armatura, CA = 10 + Des + Car.' },
        { level: 6, name: 'Affinità elementale', description: 'Scegli acido, freddo, fuoco, fulmine o veleno: resistenza e + Car ai danni di quel tipo.' },
        { level: 14, name: 'Ali di drago', description: 'Azione bonus: ali per 1 ora, Velocità di volare 18 m. Una volta per riposo lungo (o 3 punti).' },
        { level: 18, name: 'Compagno draconico', description: 'Puoi lanciare Evoca drago senza componenti materiali, e senza slot una volta per riposo lungo.' },
      ],
    },
  ],
  equipment: [
    { label: 'Lancia, 2 pugnali, focus arcano, dotazione da esploratore di dungeon e 28 mo', kit: [{ item: 'spear' }, { item: 'dagger', qty: 2 }, { item: 'arcaneFocus' }, { item: 'dungeoneersPack' }], gold: 28 },
    { label: '50 mo', kit: [], gold: 50 },
  ],
};

const INVOCATIONS: ClassChoice = {
  key: 'invocations',
  label: 'Suppliche occulte',
  level: 1,
  count: byLevel([[1, 1], [2, 3], [5, 5], [7, 6], [9, 7], [12, 8], [15, 9], [18, 10]]),
  options: [
    { id: 'pactOfTheBlade', name: 'Patto della lama', description: 'Evochi o leghi un’arma del patto; usi il Carisma per attacchi e danni.' },
    { id: 'pactOfTheChain', name: 'Patto della catena', description: 'Trovare famiglio con forme speciali (imp, pseudodrago, quasit, sprite…).' },
    { id: 'pactOfTheTome', name: 'Patto del tomo', description: 'Un Libro delle ombre con 3 trucchetti e 2 rituali di 1° livello da qualsiasi lista.' },
    { id: 'agonizingBlast', name: 'Deflagrazione agonizzante', description: '+ Car ai danni di un trucchetto da warlock che infligge danni.', level: 2 },
    { id: 'armorOfShadows', name: 'Armatura d’ombre', description: 'Armatura magica su te stesso a volontà.' },
    { id: 'devilsSight', name: 'Vista del diavolo', description: 'Vedi normalmente nell’oscurità, anche magica, entro 36 m.', level: 2 },
    { id: 'eldritchMind', name: 'Mente occulta', description: 'Vantaggio ai TS di concentrazione.' },
    { id: 'eldritchSpear', name: 'Lancia occulta', description: 'Un trucchetto da warlock guadagna 9 m × livello di gittata.', level: 2 },
    { id: 'fiendishVigor', name: 'Vigore immondo', description: 'Falsa vita su te stesso a volontà, con PF temporanei massimi.', level: 2 },
    { id: 'maskOfManyFaces', name: 'Maschera dai molti volti', description: 'Camuffare se stesso a volontà.', level: 2 },
    { id: 'mistyVisions', name: 'Visioni nebbiose', description: 'Immagine silenziosa a volontà.', level: 2 },
    { id: 'otherworldlyLeap', name: 'Balzo ultraterreno', description: 'Saltare su te stesso a volontà.', level: 2 },
    { id: 'repellingBlast', name: 'Deflagrazione repulsiva', description: 'Un trucchetto da warlock che colpisce spinge il bersaglio di 3 m.', level: 2 },
    { id: 'thirstingBlade', name: 'Lama assetata', description: 'Con l’arma del patto attacchi due volte.', level: 5 },
    { id: 'oneWithShadows', name: 'Uno con le ombre', description: 'In penombra o oscurità diventi Invisibile con un’azione Magia.', level: 5 },
    { id: 'lifedrinker', name: 'Bevitore di vita', description: 'Con l’arma del patto +1d6 danni necrotici, psichici o radiosi e cure.', level: 9 },
    { id: 'witchSight', name: 'Vista stregata', description: 'Vista pura entro 9 m.', level: 15 },
  ],
};

export const WARLOCK: ClassDef = {
  id: 'warlock',
  name: 'Warlock',
  description: 'Occultista legato a un patrono ultraterreno.',
  hitDie: 8,
  primary: ['cha'],
  saves: ['wis', 'cha'],
  skillChoices: 2,
  skillList: ['arcana', 'deception', 'history', 'intimidation', 'investigation', 'nature', 'religion'],
  armor: ['light'],
  martial: false,
  spellcasting: { ability: 'cha', type: 'pact', cantrips: cantrips(2), prepared: [2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15] },
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Patrono ultraterreno',
  choices: [INVOCATIONS],
  resources: [
    { id: 'magicalCunning', name: 'Astuzia magica', level: 2, recharge: 'long', max: () => 1 },
    { id: 'mysticArcanum', name: 'Arcanum mistico', level: 11, recharge: 'long', max: (l) => (l >= 17 ? 4 : l >= 15 ? 3 : l >= 13 ? 2 : 1) },
  ],
  features: [
    { level: 1, name: 'Suppliche occulte', description: 'Doni occulti scelti dall’elenco (1 al 1°, 3 al 2°, fino a 10).' },
    { level: 1, name: 'Magia del patto', description: 'Pochi slot, sempre del livello più alto disponibile, recuperati con un riposo breve. Usi il Carisma.' },
    { level: 2, name: 'Astuzia magica', description: 'Con 1 minuto di rituale recuperi metà degli slot del patto. Una volta per riposo lungo.' },
    { level: 9, name: 'Contattare patrono', description: 'Hai sempre preparato Contattare altri piani: puoi lanciarlo senza slot una volta per riposo lungo e superi automaticamente il suo TS.' },
    { level: 11, name: 'Arcanum mistico', description: 'Un incantesimo di 6° livello da lanciare una volta per riposo lungo (7° al 13°, 8° al 15°, 9° al 17°).' },
    EPIC,
    { level: 20, name: 'Maestro dell’occulto', description: 'Astuzia magica recupera tutti gli slot del patto.' },
  ],
  subclasses: [
    {
      id: 'fiend',
      name: 'Patrono immondo',
      description: 'Un patto con un signore dei Piani Inferiori.',
      spells: [
        { level: 3, spells: ['burningHands', 'command', 'scorchingRay', 'suggestion'] },
        { level: 5, spells: ['fireball', 'stinkingCloud'] },
        { level: 7, spells: ['fireShield', 'wallOfFire'] },
        { level: 9, spells: ['geas', 'insectPlague'] },
      ],
      features: [
        { level: 3, name: 'Benedizione dell’oscuro', description: 'Quando un nemico scende a 0 PF entro 3 m, ottieni PF temporanei pari a Car + livello.' },
        { level: 6, name: 'Fortuna dell’oscuro', description: 'Aggiungi 1d10 a una prova o TS dopo il tiro (usi pari al mod. di Carisma).' },
        { level: 10, name: 'Resilienza immonda', description: 'Dopo un riposo scegli un tipo di danno (non forza): hai resistenza.' },
        { level: 14, name: 'Scagliare all’inferno', description: 'Quando colpisci, il bersaglio fa un TS su Carisma o subisce 8d10 danni psichici. Una volta per riposo lungo.' },
      ],
    },
  ],
  equipment: [
    {
      label: 'Armatura di cuoio, falcetto, 2 pugnali, focus arcano, libro, dotazione da studioso e 15 mo',
      kit: [{ item: 'leather' }, { item: 'sickle' }, { item: 'dagger', qty: 2 }, { item: 'arcaneFocus' }, { item: 'book' }, { item: 'scholarsPack' }],
      gold: 15,
    },
    { label: '100 mo', kit: [], gold: 100 },
  ],
};

export const WIZARD: ClassDef = {
  id: 'wizard',
  name: 'Mago',
  description: 'Studioso della magia arcana.',
  hitDie: 6,
  primary: ['int'],
  saves: ['int', 'wis'],
  skillChoices: 2,
  skillList: ['arcana', 'history', 'insight', 'investigation', 'medicine', 'nature', 'religion'],
  armor: [],
  martial: false,
  spellcasting: { ability: 'int', type: 'full', cantrips: cantrips(3), prepared: [4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 16, 17, 18, 19, 21, 22, 23, 24, 25] },
  expertise: [{ level: 2, count: 1, from: ['arcana', 'history', 'investigation', 'medicine', 'nature', 'religion'] }],
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Tradizione arcana',
  resources: [{ id: 'arcaneRecovery', name: 'Recupero arcano', level: 1, recharge: 'long', max: () => 1 }],
  features: [
    { level: 1, name: 'Incantesimi', description: 'Lanci incantesimi da mago usando l’Intelligenza; il libro degli incantesimi contiene quelli che puoi preparare.' },
    { level: 1, name: 'Rituali', description: 'Puoi lanciare come rituale qualsiasi incantesimo rituale del tuo libro, anche se non preparato.' },
    { level: 1, name: 'Recupero arcano', description: 'Dopo un riposo breve recuperi slot per un totale di livelli pari a metà del livello da mago (nessuno di 6° o più). Una volta per riposo lungo.' },
    { level: 2, name: 'Studioso', description: 'Maestria in Arcano, Storia, Indagare, Medicina, Natura o Religione.' },
    { level: 5, name: 'Memorizzare incantesimo', description: 'Dopo un riposo breve puoi sostituire un incantesimo preparato con un altro del libro.' },
    { level: 18, name: 'Padronanza degli incantesimi', description: 'Un incantesimo di 1° e uno di 2° livello lanciabili a volontà al livello più basso.' },
    EPIC,
    { level: 20, name: 'Incantesimi distintivi', description: 'Due incantesimi di 3° livello sempre preparati, lanciabili una volta ciascuno per riposo breve senza slot.' },
  ],
  subclasses: [
    {
      id: 'evoker',
      name: 'Invocatore',
      description: 'Maestro dell’energia elementale distruttiva.',
      features: [
        { level: 3, name: 'Sapiente di invocazione', description: 'Due incantesimi di invocazione gratuiti nel libro, e uno a ogni nuovo livello di slot.' },
        { level: 3, name: 'Trucchetto potente', description: 'I tuoi trucchetti che infliggono danni fanno metà danni anche se mancano o il TS è superato.' },
        { level: 6, name: 'Scolpire incantesimi', description: 'Scegli creature (1 + livello dell’incantesimo) che superano automaticamente i TS delle tue invocazioni senza subire danni.' },
        { level: 10, name: 'Invocazione potenziata', description: '+ Int a un tiro di danno delle tue invocazioni.' },
        { level: 14, name: 'Sovraccarico', description: 'Un incantesimo di 1°-5° livello infligge danni massimi; dal secondo uso subisci danni necrotici.' },
      ],
    },
  ],
  equipment: [
    { label: '2 pugnali, bastone ferrato (focus), veste, libro degli incantesimi, dotazione da studioso e 5 mo', kit: [{ item: 'dagger', qty: 2 }, { item: 'quarterstaff' }, { item: 'robe' }, { item: 'spellbook' }, { item: 'scholarsPack' }], gold: 5 },
    { label: '55 mo', kit: [], gold: 55 },
  ],
};
