import { STANDARD_ASI, type ClassDef } from './classes-types';

const byLevel = (steps: [number, number][]) => Array.from({ length: 20 }, (_, i) => {
  let v = 0;
  for (const [lvl, val] of steps) if (i + 1 >= lvl) v = val;
  return v;
});

const pos = (n: number) => Math.max(1, n);

export const BARBARIAN: ClassDef = {
  id: 'barbarian',
  name: 'Barbaro',
  description: 'Guerriero primordiale alimentato dalla furia.',
  hitDie: 12,
  primary: ['str'],
  saves: ['str', 'con'],
  skillChoices: 2,
  skillList: ['animalHandling', 'athletics', 'intimidation', 'nature', 'perception', 'survival'],
  armor: ['light', 'medium', 'shield'],
  martial: true,
  masteries: byLevel([[1, 2], [4, 3], [10, 4]]),
  unarmoredDefense: 'con',
  speedBonus: (l) => (l >= 5 ? 3 : 0),
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Sentiero primordiale',
  resources: [
    {
      id: 'rage',
      name: 'Ira',
      level: 1,
      recharge: 'long',
      max: (l) => (l >= 17 ? 6 : l >= 12 ? 5 : l >= 6 ? 4 : l >= 3 ? 3 : 2),
      die: (l) => `+${l >= 16 ? 4 : l >= 9 ? 3 : 2} danni`,
    },
  ],
  features: [
    { level: 1, name: 'Ira', description: 'Azione bonus: resistenza ai danni contundenti, perforanti e taglienti, bonus ai danni con attacchi di Forza, Vantaggio a prove e TS di Forza. Dura fino alla fine del tuo prossimo turno e si estende attaccando o costringendo a un TS; massimo 10 minuti. Niente armatura pesante né concentrazione. Recuperi un uso con un riposo breve.' },
    { level: 1, name: 'Difesa senza armatura', description: 'Senza armatura, CA = 10 + Des + Cos (puoi usare uno scudo).' },
    { level: 1, name: 'Maestria nelle armi', description: 'Usi le proprietà di maestria di 2 tipi di armi da mischia (3 al 4°, 4 al 10°). Puoi cambiarne una a ogni riposo lungo.' },
    { level: 2, name: 'Percepire il pericolo', description: 'Vantaggio ai TS su Destrezza se non sei Incapacitato.' },
    { level: 2, name: 'Attacco irruento', description: 'Al primo attacco del turno puoi attaccare con Vantaggio usando la Forza; fino al tuo prossimo turno gli attacchi contro di te hanno Vantaggio.' },
    { level: 3, name: 'Conoscenza primordiale', description: 'Una competenza extra tra le abilità del barbaro. In Ira puoi usare la Forza per Acrobazia, Furtività, Intimidire, Percezione e Sopravvivenza.' },
    { level: 5, name: 'Attacco extra', description: 'Attacchi due volte con l’azione di Attacco.' },
    { level: 5, name: 'Movimento veloce', description: '+3 m di Velocità senza armatura pesante.' },
    { level: 7, name: 'Istinto ferino', description: 'Vantaggio ai tiri di iniziativa.' },
    { level: 7, name: 'Balzo istintivo', description: 'Quando entri in Ira puoi muoverti di metà della tua Velocità.' },
    { level: 9, name: 'Colpo brutale', description: 'Rinunciando al Vantaggio dell’Attacco irruento, se colpisci infliggi +1d10 e un effetto: Colpo possente (spingi di 4,5 m) o Colpo lacerante (−4,5 m di Velocità al bersaglio).' },
    { level: 11, name: 'Ira implacabile', description: 'Se scendi a 0 PF in Ira, TS su Costituzione CD 10 (+5 per ogni uso): se superato hai PF pari al doppio del livello.' },
    { level: 13, name: 'Colpo brutale migliorato', description: 'Nuovi effetti: Colpo sbalorditivo (Svantaggio al prossimo TS del bersaglio) e Colpo lacerante (niente reazioni).' },
    { level: 15, name: 'Ira persistente', description: 'Tirando l’iniziativa recuperi tutte le Ire (una volta per riposo lungo); l’Ira dura 10 minuti senza doverla mantenere.' },
    { level: 17, name: 'Colpo brutale migliorato', description: 'Il danno del Colpo brutale sale a 2d10 e puoi applicare due effetti.' },
    { level: 18, name: 'Potenza indomita', description: 'Se il totale di una prova o TS di Forza è inferiore al tuo punteggio di Forza, usi il punteggio.' },
    { level: 19, name: 'Dono epico', description: 'Ottieni un talento Dono epico.' },
    { level: 20, name: 'Campione primordiale', description: 'Forza e Costituzione +4 (massimo 25).' },
  ],
  subclasses: [
    {
      id: 'berserker',
      name: 'Sentiero del berserker',
      description: 'La furia come violenza pura.',
      features: [
        { level: 3, name: 'Frenesia', description: 'In Ira, con l’Attacco irruento, il primo bersaglio colpito nel turno subisce danni extra pari a tanti d6 quanto il bonus ai danni dell’Ira.' },
        { level: 6, name: 'Ira incurante', description: 'Immunità ad Affascinato e Spaventato in Ira; entrando in Ira termini questi effetti.' },
        { level: 10, name: 'Rappresaglia', description: 'Reazione: quando una creatura entro 1,5 m ti danneggia, la attacchi in mischia.' },
        { level: 14, name: 'Presenza intimidatoria', description: 'Azione bonus: le creature scelte entro 9 m fanno TS su Saggezza o sono Spaventate per 1 minuto. Una volta per riposo lungo (o spendendo un uso di Ira).' },
      ],
    },
  ],
  equipment: [
    { label: 'Ascia bipenne, 4 asce, dotazione da esploratore e 15 mo', kit: [{ item: 'greataxe' }, { item: 'handaxe', qty: 4 }, { item: 'explorersPack' }], gold: 15 },
    { label: '75 mo', kit: [], gold: 75 },
  ],
};

export const FIGHTER: ClassDef = {
  id: 'fighter',
  name: 'Guerriero',
  description: 'Maestro di armi, armature e tattiche.',
  hitDie: 10,
  primary: ['str', 'dex'],
  saves: ['str', 'con'],
  skillChoices: 2,
  skillList: ['acrobatics', 'animalHandling', 'athletics', 'history', 'insight', 'intimidation', 'persuasion', 'perception', 'survival'],
  armor: ['light', 'medium', 'heavy', 'shield'],
  martial: true,
  masteries: byLevel([[1, 3], [4, 4], [10, 5], [16, 6]]),
  asiLevels: [4, 6, 8, 12, 14, 16, 19],
  subclassLevel: 3,
  subclassLabel: 'Archetipo marziale',
  choices: [{ key: 'fightingStyle', label: 'Stile di combattimento', level: 1, options: [] }],
  resources: [
    { id: 'secondWind', name: 'Recuperare energie', level: 1, recharge: 'long', shortRestOne: true, max: (l) => (l >= 10 ? 4 : l >= 4 ? 3 : 2), die: (l) => `1d10+${l}` },
    { id: 'actionSurge', name: 'Azione impetuosa', level: 2, recharge: 'short', max: (l) => (l >= 17 ? 2 : 1) },
    { id: 'indomitable', name: 'Indomabile', level: 9, recharge: 'long', max: (l) => (l >= 17 ? 3 : l >= 13 ? 2 : 1) },
  ],
  features: [
    { level: 1, name: 'Stile di combattimento', description: 'Un talento Stile di combattimento a scelta; puoi cambiarlo quando sali di livello.' },
    { level: 1, name: 'Recuperare energie', description: 'Azione bonus: recuperi 1d10 + livello da guerriero PF. Recuperi un uso con un riposo breve.' },
    { level: 1, name: 'Maestria nelle armi', description: 'Usi la maestria di 3 tipi di armi (4 al 4°, 5 al 10°, 6 al 16°).' },
    { level: 2, name: 'Azione impetuosa', description: 'Nel tuo turno ottieni un’azione aggiuntiva (non Magia). Una volta per riposo breve (due al 17°).' },
    { level: 2, name: 'Mente tattica', description: 'Quando fallisci una prova di caratteristica, puoi spendere un uso di Recuperare energie per aggiungere 1d10; se fallisci ancora l’uso non viene speso.' },
    { level: 5, name: 'Attacco extra', description: 'Attacchi due volte con l’azione di Attacco.' },
    { level: 5, name: 'Cambio tattico', description: 'Quando usi Recuperare energie ti muovi di metà Velocità senza provocare attacchi di opportunità.' },
    { level: 9, name: 'Indomabile', description: 'Ripeti un TS fallito aggiungendo il livello da guerriero. Una volta per riposo lungo (2 al 13°, 3 al 17°).' },
    { level: 9, name: 'Maestro tattico', description: 'Quando attacchi con un’arma di cui usi la maestria, puoi sostituirla con Spingere, Fiaccare o Rallentare.' },
    { level: 11, name: 'Due attacchi extra', description: 'Attacchi tre volte con l’azione di Attacco.' },
    { level: 13, name: 'Attacchi studiati', description: 'Se manchi una creatura, hai Vantaggio al prossimo attacco contro di lei entro la fine del tuo prossimo turno.' },
    { level: 19, name: 'Dono epico', description: 'Ottieni un talento Dono epico.' },
    { level: 20, name: 'Tre attacchi extra', description: 'Attacchi quattro volte con l’azione di Attacco.' },
  ],
  subclasses: [
    {
      id: 'champion',
      name: 'Campione',
      description: 'Eccellenza atletica e colpi devastanti.',
      features: [
        { level: 3, name: 'Critico migliorato', description: 'I tuoi attacchi con armi e colpi senz’armi sono critici con 19 o 20.' },
        { level: 3, name: 'Atleta straordinario', description: 'Vantaggio all’iniziativa e alle prove di Atletica; dopo un critico ti muovi di metà Velocità senza provocare attacchi di opportunità.' },
        { level: 7, name: 'Stile di combattimento aggiuntivo', description: 'Un altro talento Stile di combattimento.' },
        { level: 10, name: 'Guerriero eroico', description: 'All’inizio del tuo turno ottieni Ispirazione eroica se non ce l’hai.' },
        { level: 15, name: 'Critico superiore', description: 'Critici con 18-20.' },
        { level: 18, name: 'Sopravvissuto', description: 'Vantaggio ai TS contro morte; se hai metà PF o meno, recuperi 5 + Cos PF all’inizio del turno.' },
      ],
    },
  ],
  equipment: [
    {
      label: 'Cotta di maglia, spadone, mazzafrusto, 8 giavellotti, dotazione da esploratore di dungeon e 4 mo',
      kit: [{ item: 'chainMail' }, { item: 'greatsword' }, { item: 'flail' }, { item: 'javelin', qty: 8 }, { item: 'dungeoneersPack' }],
      gold: 4,
    },
    {
      label: 'Cuoio borchiato, scimitarra, spada corta, arco lungo, 20 frecce, faretra, dotazione da esploratore di dungeon e 11 mo',
      kit: [{ item: 'studded' }, { item: 'scimitar' }, { item: 'shortsword' }, { item: 'longbow' }, { item: 'arrows' }, { item: 'quiver' }, { item: 'dungeoneersPack' }],
      gold: 11,
    },
    { label: '155 mo', kit: [], gold: 155 },
  ],
};

export const MONK: ClassDef = {
  id: 'monk',
  name: 'Monaco',
  description: 'Artista marziale che canalizza l’energia interiore.',
  hitDie: 8,
  primary: ['dex', 'wis'],
  saves: ['str', 'dex'],
  skillChoices: 2,
  skillList: ['acrobatics', 'athletics', 'history', 'insight', 'religion', 'stealth'],
  armor: [],
  martial: 'light',
  tools: 'Uno strumento da artigiano o musicale',
  unarmoredDefense: 'wis',
  speedBonus: (l) => (l >= 18 ? 9 : l >= 14 ? 7.5 : l >= 10 ? 6 : l >= 6 ? 4.5 : l >= 2 ? 3 : 0),
  asiLevels: STANDARD_ASI,
  subclassLevel: 3,
  subclassLabel: 'Tradizione monastica',
  resources: [
    { id: 'focus', name: 'Punti focus', level: 2, recharge: 'short', max: (l) => l },
    { id: 'martialArts', name: 'Dado delle arti marziali', level: 1, recharge: 'long', max: () => 0, die: (l) => (l >= 17 ? '1d12' : l >= 11 ? '1d10' : l >= 5 ? '1d8' : '1d6') },
  ],
  features: [
    { level: 1, name: 'Arti marziali', description: 'Senza armatura né scudo: colpi senz’armi e armi da monaco usano Destrezza e il dado delle arti marziali (d6, d8 al 5°, d10 all’11°, d12 al 17°); un colpo senz’armi come azione bonus.' },
    { level: 1, name: 'Difesa senza armatura', description: 'Senza armatura né scudo, CA = 10 + Des + Sag.' },
    { level: 2, name: 'Focus del monaco', description: 'Punti focus pari al livello. Raffica di colpi (due colpi senz’armi come azione bonus), Difesa paziente e Passo del vento (Disimpegno o Scatto come azione bonus; con 1 punto entrambi). Recuperi con riposo breve.' },
    { level: 2, name: 'Movimento senza armatura', description: '+3 m di Velocità senza armatura né scudo (aumenta con i livelli).' },
    { level: 2, name: 'Metabolismo straordinario', description: 'Tirando l’iniziativa recuperi tutti i punti focus e PF pari a un dado delle arti marziali + livello. Una volta per riposo lungo.' },
    { level: 3, name: 'Deviare attacchi', description: 'Reazione: riduci i danni di un attacco di 1d10 + Des + livello; se a 0, con 1 punto focus rimandi il colpo.' },
    { level: 4, name: 'Caduta lenta', description: 'Reazione: riduci i danni da caduta di 5 × livello.' },
    { level: 5, name: 'Attacco extra', description: 'Attacchi due volte con l’azione di Attacco.' },
    { level: 5, name: 'Colpo stordente', description: 'Una volta per turno, quando colpisci, spendi 1 punto focus: TS su Costituzione o il bersaglio è Stordito fino al tuo prossimo turno (se lo supera, Velocità dimezzata e Vantaggio al prossimo attacco contro di lui).' },
    { level: 6, name: 'Colpi potenziati', description: 'I colpi senz’armi possono infliggere danni da forza.' },
    { level: 7, name: 'Elusione', description: 'Con un TS su Destrezza per dimezzare i danni: nessun danno se superato, metà se fallito.' },
    { level: 9, name: 'Movimento acrobatico', description: 'Puoi muoverti su superfici verticali e sui liquidi durante il tuo movimento.' },
    { level: 10, name: 'Focus accresciuto', description: 'Raffica di colpi fa tre colpi; Difesa paziente e Passo del vento migliorano.' },
    { level: 10, name: 'Autoripristino', description: 'A fine turno puoi terminare su di te Affascinato, Spaventato o Avvelenato; non soffri di Indebolimento per fame o sete.' },
    { level: 13, name: 'Deviare energia', description: 'Deviare attacchi funziona contro qualsiasi tipo di danno.' },
    { level: 14, name: 'Sopravvissuto disciplinato', description: 'Competenza in tutti i TS; spendi 1 punto focus per ripetere un TS fallito.' },
    { level: 15, name: 'Focus perfetto', description: 'Tirando l’iniziativa, se hai 3 punti focus o meno, risali a 4.' },
    { level: 18, name: 'Difesa superiore', description: 'Con 3 punti focus: resistenza a tutti i danni tranne forza per 1 minuto.' },
    { level: 19, name: 'Dono epico', description: 'Ottieni un talento Dono epico.' },
    { level: 20, name: 'Corpo e mente', description: 'Destrezza e Saggezza +4 (massimo 25).' },
  ],
  subclasses: [
    {
      id: 'openHand',
      name: 'Guerriero della mano aperta',
      description: 'Maestro del combattimento senz’armi.',
      features: [
        { level: 3, name: 'Tecnica della mano aperta', description: 'Con la Raffica di colpi ogni colpo può: impedire le reazioni, spingere di 4,5 m (TS For) o far cadere Prono (TS Des).' },
        { level: 6, name: 'Integrità del corpo', description: 'Azione bonus: recuperi PF pari a un dado delle arti marziali + Sag. Usi pari al mod. di Saggezza per riposo lungo.' },
        { level: 11, name: 'Passo rapido', description: 'Dopo un’azione bonus diversa da Passo del vento puoi usarlo subito.' },
        { level: 17, name: 'Palmo tremante', description: 'Con 4 punti focus imprimi vibrazioni letali: poi un TS su Costituzione, 10d12 danni da forza (metà se superato).' },
      ],
    },
  ],
  equipment: [
    { label: 'Lancia, 5 pugnali, uno strumento, dotazione da esploratore e 11 mo', kit: [{ item: 'spear' }, { item: 'dagger', qty: 5 }, { item: 'artisansTools' }, { item: 'explorersPack' }], gold: 11 },
    { label: '50 mo', kit: [], gold: 50 },
  ],
};

export const ROGUE: ClassDef = {
  id: 'rogue',
  name: 'Ladro',
  description: 'Esperto furtivo che colpisce i punti deboli.',
  hitDie: 8,
  primary: ['dex'],
  saves: ['dex', 'int'],
  skillChoices: 4,
  skillList: ['acrobatics', 'athletics', 'deception', 'insight', 'intimidation', 'investigation', 'perception', 'persuasion', 'sleightOfHand', 'stealth'],
  armor: ['light'],
  martial: 'finesseOrLight',
  tools: 'Arnesi da scasso',
  masteries: byLevel([[1, 2]]),
  expertise: [
    { level: 1, count: 2 },
    { level: 6, count: 2 },
  ],
  asiLevels: [4, 8, 10, 12, 16, 19],
  subclassLevel: 3,
  subclassLabel: 'Archetipo ladresco',
  resources: [
    { id: 'sneakAttack', name: 'Attacco furtivo', level: 1, recharge: 'long', max: () => 0, die: (l) => `${Math.ceil(l / 2)}d6` },
    { id: 'strokeOfLuck', name: 'Colpo di fortuna', level: 20, recharge: 'short', max: () => 1 },
  ],
  features: [
    { level: 1, name: 'Maestria', description: 'Raddoppi la competenza in due abilità (altre due al 6°).' },
    { level: 1, name: 'Attacco furtivo', description: 'Una volta per turno, +Xd6 a un attacco con arma accurata o a distanza se hai Vantaggio, o se un alleato è entro 1,5 m dal bersaglio e non hai Svantaggio.' },
    { level: 1, name: 'Gergo ladresco', description: 'Conosci il gergo ladresco e un’altra lingua.' },
    { level: 1, name: 'Maestria nelle armi', description: 'Usi la maestria di 2 tipi di armi.' },
    { level: 2, name: 'Azione astuta', description: 'Scatto, Disimpegno o Nascondersi come azione bonus.' },
    { level: 3, name: 'Mira stabile', description: 'Azione bonus: Vantaggio al prossimo attacco del turno se non ti sei mosso (Velocità 0 fino a fine turno).' },
    { level: 5, name: 'Colpo astuto', description: 'Rinunci a dadi dell’Attacco furtivo per effetti: Veleno (1d6), Inciampo (1d6), Ritirata (1d6).' },
    { level: 5, name: 'Schivata prodigiosa', description: 'Reazione: dimezzi i danni di un attacco che vedi.' },
    { level: 7, name: 'Elusione', description: 'Nessun danno se superi un TS su Destrezza per dimezzare, metà se lo fallisci.' },
    { level: 7, name: 'Talento affidabile', description: 'Nelle prove di abilità in cui hai competenza, un 9 o meno sul d20 conta come 10.' },
    { level: 11, name: 'Colpo astuto migliorato', description: 'Puoi applicare due effetti di Colpo astuto.' },
    { level: 14, name: 'Colpi subdoli', description: 'Nuovi effetti: Stordire (2d6), Tramortire (6d6), Oscurare (3d6).' },
    { level: 15, name: 'Mente scivolosa', description: 'Competenza nei TS su Saggezza e Carisma.' },
    { level: 18, name: 'Inafferrabile', description: 'Nessun tiro per colpire contro di te ha Vantaggio se non sei Incapacitato.' },
    { level: 19, name: 'Dono epico', description: 'Ottieni un talento Dono epico.' },
    { level: 20, name: 'Colpo di fortuna', description: 'Trasformi una prova d20 fallita in un 20. Una volta per riposo breve.' },
  ],
  subclasses: [
    {
      id: 'thief',
      name: 'Furfante',
      description: 'Scasso, destrezza e oggetti magici.',
      features: [
        { level: 3, name: 'Mani veloci', description: 'Con l’Azione astuta puoi fare Rapidità di Mano, usare arnesi da scasso o l’azione Utilizzare.' },
        { level: 3, name: 'Scalatore', description: 'Velocità di scalare pari alla Velocità; salti più lontano usando la Destrezza.' },
        { level: 9, name: 'Furtività suprema', description: 'Nuovo Colpo astuto: Attacco furtivo senza perdere lo stato di Nascosto (1d6).' },
        { level: 13, name: 'Usare oggetti magici', description: 'Tre oggetti in sintonia, ignori requisiti di classe, e le pergamene di incantesimi funzionano per te.' },
        { level: 17, name: 'Riflessi del ladro', description: 'Nel primo round di combattimento fai due turni.' },
      ],
    },
  ],
  equipment: [
    {
      label: 'Armatura di cuoio, 2 pugnali, spada corta, arco corto, 20 frecce, faretra, arnesi da scasso, dotazione da scassinatore e 8 mo',
      kit: [{ item: 'leather' }, { item: 'dagger', qty: 2 }, { item: 'shortsword' }, { item: 'shortbow' }, { item: 'arrows' }, { item: 'quiver' }, { item: 'thievesTools' }, { item: 'burglarsPack' }],
      gold: 8,
    },
    { label: '100 mo', kit: [], gold: 100 },
  ],
};

export { byLevel, pos };
