import type { CharId, SkillId, Speed } from './data';
import { CHARACTERISTICS } from './data';

/**
 * Profili dei PNG dalla Guida del Gamemaster. Servitori: sconfitti alla prima
 * Ferita. Bruti e Mostruosità: il tracciato dice cosa succede a ogni Ferita.
 * Campioni: tirano sulla tabella delle Ferite come i personaggi.
 */

export type NpcType = 'Servitore' | 'Bruto' | 'Campione' | 'Mostruosità';

export interface NpcAttack {
  name: string;
  range: string;
  dice: number;
  target: number;
  /** null: niente Danno (infligge una Condizione o un effetto) */
  damage: number | null;
  hands?: 1 | 2;
  traits?: string;
  ignoresArmour?: boolean;
}

export interface NpcProtection {
  skill: 'Atletica' | 'Difesa' | 'Furtività';
  dice: number;
  target: number;
  shield?: boolean;
}

export interface Npc {
  id: string;
  name: string;
  group: string;
  type: NpcType;
  chars: Record<CharId, number>;
  speed: Speed;
  /** null: non subisce Danni (sciami) */
  resilience: number | null;
  armoured: boolean;
  /** Bruti e Mostruosità: soglie di Ferite ed effetti; l’ultima è "Sconfitto" */
  track?: { at: string; effect: string }[];
  /** quante Ferite lo sconfiggono (1 per i Servitori) */
  maxWounds: number | null;
  skills: Partial<Record<SkillId, number>>;
  /** valore di tutte le altre Abilità */
  other: number;
  attacks: NpcAttack[];
  protection: NpcProtection[];
  abilities: { name: string; text: string }[];
  /** Livello da Mago e incantesimi conosciuti */
  mage?: { level: number; spells: { name: string; vm: number; text: string }[] };
  gear?: string;
}

const SK: Record<string, SkillId> = {
  Mischia: 'mischia', Difesa: 'difesa', Tiro: 'tiro', Lancio: 'lancio', Muscoli: 'muscoli', Lavoro: 'lavoro', Sopravvivenza: 'sopravvivenza',
  Tempra: 'tempra', Percezione: 'percezione', Destrezza: 'destrezza', Atletica: 'atletica', Furtività: 'furtivita', Volontà: 'volonta',
  Memoria: 'memoria', Comando: 'comando', Fascino: 'fascino',
};

/** "Mischia 4, Volontà 3, Altro 2" */
function skills(s: string): { skills: Partial<Record<SkillId, number>>; other: number } {
  const out: Partial<Record<SkillId, number>> = {};
  let other = 2;
  for (const part of s.split(',')) {
    const m = /^\s*(.+?)\s+(\d+)\s*$/.exec(part);
    if (!m) continue;
    if (m[1] === 'Altro') other = Number(m[2]);
    else if (SK[m[1]!]) out[SK[m[1]!]!] = Number(m[2]);
  }
  return { skills: out, other };
}

/** "Nome|Portata|3d/4|Danno|mani|tratti" (Danno "-" se non ne fa) */
function attack(s: string): NpcAttack {
  const [name, range, pool, dmg, hands, traits] = s.split('|');
  const [dice, target] = pool!.replace('d', '').split('/').map(Number);
  const tr = traits?.trim() || undefined;
  return {
    name: name!.trim(), range: range!.trim(), dice: dice!, target: target!,
    damage: dmg && dmg.trim() !== '-' ? Number(dmg) : null,
    hands: hands === '2' ? 2 : hands === '1' ? 1 : undefined,
    traits: tr,
    ignoresArmour: tr ? /ignora l.armatura/i.test(tr) : undefined,
  };
}

/** "Atletica 3/2, Difesa 4/4 scudo" */
function protection(s: string): NpcProtection[] {
  return s.split(',').map((p) => {
    const m = /(Atletica|Difesa|Furtività)\s+(\d+)\/(\d+)(\s*scudo)?/.exec(p)!;
    return { skill: m[1] as NpcProtection['skill'], dice: Number(m[2]), target: Number(m[3]), shield: !!m[4] || undefined };
  });
}

const slug = (s: string) =>
  s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[’']/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

interface Def {
  name: string;
  group: string;
  type: NpcType;
  chars: string;
  speed: Speed;
  res: number | null;
  armoured?: boolean;
  track?: [string, string][];
  skills: string;
  attacks: string[];
  prot: string;
  abilities: [string, string][];
  mage?: { level: number; spells: [string, number, string][] };
  gear?: string;
}

function npc(d: Def): Npc {
  const values = d.chars.trim().split(/\s+/).map(Number);
  const chars = Object.fromEntries(CHARACTERISTICS.map((c, i) => [c, values[i] ?? 0])) as Record<CharId, number>;
  const track = d.track?.map(([at, effect]) => ({ at, effect }));
  const last = track?.[track.length - 1]?.at;
  const maxWounds = d.res === null ? null : d.type === 'Servitore' ? 1 : d.type === 'Campione' ? null : last ? Number(/(\d+)\D*$/.exec(last)?.[1] ?? 1) : 1;
  return {
    id: slug(d.name), name: d.name, group: d.group, type: d.type, chars, speed: d.speed, resilience: d.res, armoured: !!d.armoured,
    track, maxWounds, ...skills(d.skills), attacks: d.attacks.map(attack), protection: protection(d.prot),
    abilities: d.abilities.map(([name, text]) => ({ name, text })),
    mage: d.mage ? { level: d.mage.level, spells: d.mage.spells.map(([name, vm, text]) => ({ name, vm, text })) } : undefined,
    gear: d.gear,
  };
}

const MAGE = (level: number) =>
  ['Incantatore', `Mago di Livello ${level}: può aggiungere dadi alla Prova di Magia aggiungendone altrettanti alla Riserva degli Incidenti Magici; una volta per round si oppone con Volontà a una Prova di Magia entro Distanza Lunga. Ogni 9 va nella Riserva.`] as [string, string];
const FEARSOME = (who: string): [string, string] => ['Spaventoso', `Chi Arretra dagli attacchi di ${who} diventa Atterrito.`];
const TERRIFYING = (who: string): [string, string] => ['Terrificante', `Chi Arretra o subisce una Ferita dagli attacchi di ${who} diventa Atterrito.`];
const FOREST: [string, string] = ['Figlio della Foresta', 'Nei boschi ignora il Terreno Difficile.'];
const FLY: [string, string] = ['Volo', 'Vola attraverso Zone verticali ignorando gli ostacoli; non può alzarsi in volo se a Distanza Ravvicinata da un nemico a terra.'];
const MONSTER_FLY: [string, string] = ['Volo Mostruoso (Reazione)', 'Vola attraverso Zone verticali. Come Reazione Arretra verso l’alto; se ha già Arretrato nel turno subisce invece una Ferita.'];
const HORDE = (who: string): [string, string] => ['Orda', `Quando ${who} Aiuta un alleato in un attacco di mischia non serve una Prova: +1d, anche oltre il massimo.`];
const UNDEAD = (who: string): [string, string] => ['Nonmorto', `${who} non mangia, non dorme e non respira; è immune agli effetti psicologici.`];
const SWARM = (n: number): [string, string][] => [
  ['Sono Dappertutto!', 'Conta sempre in superiorità numerica (già incluso) e chi è nella sua Zona è a Distanza Ravvicinata; si attraversa senza penalità.'],
  ['Sterminio', `Non subisce Ferite né Condizioni: si sconfigge con una Prova Prolungata di ${n} successi (un’Azione a Prova) con un’Abilità offensiva o l’ambiente, oppure con un Pericolo o un effetto che copre tutta la Zona.`],
];

const DEFS: Def[] = [
  // ---------------------------------------------------------------- Popolani
  { name: 'Artigiano', group: 'Popolani e criminali', type: 'Servitore', chars: '2 2 3 3 3 3 3 2', speed: 'Normale', res: 3, skills: 'Destrezza 4, Lavoro 4, Volontà 3, Altro 2', attacks: ['Armi Improvvisate|Ravvicinata|2d/2|2|1|'], prot: 'Atletica 3/2', abilities: [['Orgoglio Professionale', 'Pagando una Moneta in più per un suo avere, la prossima Prova con quell’avere ha +1d.']], gear: 'Abiti da lavoro in cuoio, attrezzi del mestiere, spiccioli (Bronzo)' },
  { name: 'Cittadino Imperiale', group: 'Popolani e criminali', type: 'Servitore', chars: '2 2 3 3 3 3 3 3', speed: 'Normale', res: 3, skills: 'Fascino 3, Memoria 3, Volontà 3, Altro 2', attacks: ['Pugnale|Ravvicinata|2d/2|2|1|'], prot: 'Atletica 2/2', abilities: [['Scaltro', '+1d a Percezione contro i borseggiatori.']], gear: 'Abbigliamento da cittadino, pugnale, spiccioli (Argento)' },
  { name: 'Contadino Imperiale', group: 'Popolani e criminali', type: 'Servitore', chars: '2 3 3 3 2 3 2 2', speed: 'Normale', res: 3, skills: 'Lavoro 3, Altro 2', attacks: ['Arco da Caccia|Media – Lunga|3d/2|3|2|', 'Armi Improvvisate|Ravvicinata|2d/2|2|1|'], prot: 'Atletica 3/2', abilities: [['Torce e Forconi', 'Quando Aiuta un alleato in mischia non serve una Prova: +1d, anche oltre il massimo.']], gear: 'Abiti da popolano, arco, attrezzi agricoli' },
  { name: 'Fuorilegge', group: 'Popolani e criminali', type: 'Servitore', chars: '3 2 3 3 3 3 2 2', speed: 'Normale', res: 3, skills: 'Atletica 3, Comando 3, Furtività 3, Mischia 3, Altro 2', attacks: ['Pugnale|Ravvicinata|3d/3|2|1|'], prot: 'Atletica 3/3', abilities: [['In Agguato', 'Fuori dalla battaglia, le Prove di Percezione per notarlo nascosto sono Tetre.']], gear: 'Abiti occultanti, pugnale, strumenti da ladro' },
  { name: 'Guardia Cittadina', group: 'Popolani e criminali', type: 'Servitore', chars: '3 3 3 3 3 3 3 3', speed: 'Normale', res: 4, armoured: true, skills: 'Atletica 3, Comando 3, Mischia 3, Muscoli 3, Percezione 3, Altro 2', attacks: ['Arma Inastata|Corta|3d/3|5|2|'], prot: 'Atletica 3/3', abilities: [['Fischietto', 'Recuperando può chiamare rinforzi: altre guardie arrivano il turno dopo e ritirarsi da loro con Atletica è Tetro.']], gear: 'Alabarda, armatura leggera, lanterna, uniforme' },
  { name: 'Brigante', group: 'Popolani e criminali', type: 'Servitore', chars: '3 3 3 3 3 3 2 2', speed: 'Normale', res: 4, armoured: true, skills: 'Comando 3, Furtività 3, Mischia 3, Tiro 3, Altro 2', attacks: ['Ascia|Ravvicinata|3d/3|3|1|', 'Arco da Guerra|Media – Lunga|3d/3|3|2|'], prot: 'Atletica 3/2', abilities: [['Vile Opportunista', 'In mischia contro un nemico in inferiorità numerica ottiene +2d invece di +1d.']], gear: 'Arco, armatura leggera, ascia, refurtiva (Bronzo)' },
  // ------------------------------------------------------- Nobili e soldati
  { name: 'Nobile Imperiale', group: 'Nobili e soldati', type: 'Campione', chars: '3 3 3 3 3 3 4 4', speed: 'Normale', res: 3, skills: 'Comando 4, Difesa 4, Mischia 4, Tiro 4, Altro 3', attacks: ['Pistola da Duello|Ravvicinata – Corta|3d/4|5|1|ignora l’armatura, ricarica 3', 'Stocco Elegante|Ravvicinata|3d/4|3|1|'], prot: 'Atletica 3/3, Difesa 3/4', abilities: [['Attento, Signore!', 'Finché ha a Distanza Ravvicinata un alleato di Status inferiore, gli attacchi contro di lui sono Tetri.']], gear: 'Pistola, spada, vesti signorili, gioielli (Oro)' },
  { name: 'Funzionario Imperiale', group: 'Nobili e soldati', type: 'Bruto', chars: '2 2 3 3 3 3 3 3', speed: 'Normale', res: 3, track: [['0 Ferite', '—'], ['1 Ferita', 'Diventa Atterrito'], ['2 Ferite', 'Sconfitto']], skills: 'Memoria 4, Percezione 4, Altro 3', attacks: ['Pistola|Ravvicinata – Corta|2d/3|5|1|ignora l’armatura, ricarica 3', 'Pugnale|Ravvicinata|2d/3|2|1|'], prot: 'Atletica 3/3', abilities: [['L’Ho Già Sentito', 'Persuaderlo o Distrarlo è Tetro, a meno di una tangente.']], gear: 'Abbigliamento da cittadino, occorrente per scrivere, pistola, tasse riscosse (Argento)' },
  { name: 'Soldato Provinciale Imperiale', group: 'Nobili e soldati', type: 'Servitore', chars: '3 3 3 3 3 3 3 3', speed: 'Normale', res: 4, armoured: true, skills: 'Difesa 4, Altro 3', attacks: ['Lancia|Corta|3d/3|3|1|', 'Alabarda|Ravvicinata|3d/3|5|2|', 'Balestra|Corta – Lunga|3d/3|4|2|', 'Archibugio|Media – Lunga|3d/3|5|2|ignora l’armatura, ricarica 3'], prot: 'Atletica 3/3, Difesa 3/4', abilities: [['Azioni di Supporto', 'Quando un nemico arriva a Distanza Ravvicinata di un Soldato Provinciale, un commilitone libero in una Zona adiacente può subito Caricare o tirare.']], gear: 'Armatura leggera, lancia o alabarda o balestra o archibugio, uniforme' },
  { name: 'Cavaliere Imperiale', group: 'Nobili e soldati', type: 'Bruto', chars: '4 3 3 3 3 3 4 3', speed: 'Normale', res: 6, armoured: true, track: [['0 Ferite', '—'], ['1 Ferita', 'Diventa Esausto'], ['2 Ferite', 'Sconfitto']], skills: 'Difesa 4, Mischia 4, Volontà 4, Altro 3', attacks: ['Lancia da Cavaliere|Ravvicinata|4d/4|4|1|+1d e +1 Danno caricando in sella'], prot: 'Atletica 2/3, Difesa 4/4 scudo', abilities: [['Nobile Destriero', 'In sella: +1 Resilienza, Veloce, e le cariche riuscite gettano Prono il bersaglio (non le Mostruosità).'], ['Per l’Ordine', 'Gli attacchi in Carica sono Gloriosi se non è Barcollante.']], gear: 'Armatura pesante, lancia da cavaliere, scudo' },
  { name: 'Miliziano della Libera Compagnia', group: 'Nobili e soldati', type: 'Servitore', chars: '3 3 3 3 3 3 2 2', speed: 'Normale', res: 3, skills: 'Atletica 3, Comando 3, Lancio 3, Mischia 3, Volontà 3, Altro 2', attacks: ['Lame Improvvisate|Ravvicinata|3d/3|3|1|', 'Proiettili Assortiti|Corta – Media|3d/3|3|1|'], prot: 'Atletica 3/3', abilities: [['Forza del Numero', 'Aiutando un alleato in mischia non serve una Prova: +1d, anche oltre il massimo.'], ['Distaccamento', 'Supporta i Soldati Provinciali: quando un nemico si avvicina a uno di loro può Caricare o tirare subito.']], gear: 'Abiti da popolano, coltelli da lancio, spada' },
  { name: 'Cecchino dell’Hochland', group: 'Nobili e soldati', type: 'Bruto', chars: '3 4 3 4 4 4 3 2', speed: 'Normale', res: 5, armoured: true, track: [['0 Ferite', '—'], ['1 Ferita', 'Perde la Mira'], ['2 Ferite', 'Sconfitto']], skills: 'Destrezza 5, Furtività 4, Percezione 4, Tiro 5, Volontà 4, Altro 3', attacks: ['Moschetto Lungo dell’Hochland|Media – Estrema|4d/5|6|2|senza Mirare è Tetro, ignora l’armatura, +1d sulle Ferite, ricarica 3', 'Ascia|Ravvicinata|3d/3|3|1|'], prot: 'Atletica 4/4', abilities: [['Ricarica Rapida', 'Dopo una ricarica riuscita può Mirare o Attaccare come seconda Azione (non se Barcollante o se si è mosso).'], ['Nido del Cecchino', 'Ignora il Terreno Difficile nei boschi.']], gear: 'Armatura leggera, ascia, moschetto lungo' },
  { name: 'Cavaliere del Lupo Bianco', group: 'Nobili e soldati', type: 'Bruto', chars: '4 3 3 3 3 3 4 3', speed: 'Normale', res: 5, armoured: true, track: [['0 Ferite', '—'], ['1 Ferita', 'Diventa Esausto'], ['2 Ferite', 'Sconfitto']], skills: 'Comando 4, Mischia 4, Volontà 4, Altro 3', attacks: ['Martello del Lupo|Ravvicinata|4d/4|5|2|+1d e +1 Danno in Carica'], prot: 'Atletica 2/3, Difesa 4/3', abilities: [['Nobile Destriero', 'In sella: +1 Resilienza, Veloce, le cariche riuscite gettano Prono il bersaglio.'], ['Carica Furiosa', 'Dopo una Carica riuscita può attaccare un altro nemico vicino come seconda Azione.']], gear: 'Armatura pesante, martello a due mani' },
  // ---------------------------------------------------------- Ogri, Halfling, Nani, Elfi
  { name: 'Ogre Imperiale', group: 'Ogri, Halfling, Nani ed Elfi', type: 'Bruto', chars: '3 3 5 5 2 3 2 2', speed: 'Veloce', res: 6, armoured: true, track: [['0 Ferite', '—'], ['1-2 Ferite', 'Velocità Normale'], ['3 Ferite', 'Sconfitto']], skills: 'Atletica 3, Comando 3, Mischia 4, Muscoli 4, Tempra 4, Volontà 3, Altro 2', attacks: ['Martello a Due Mani|Ravvicinata|2d/4|8|2|', 'Spinta Violenta|Ravvicinata|5d/4|-||getta Prono', 'Pistola Ogre|Ravvicinata – Media|3d/2|5|1|ignora l’armatura, ricarica 3'], prot: 'Atletica 3/3', abilities: [['Carica Ogre', 'Se una Spinta Violenta in Carica va a segno, attacca di nuovo con un’altra arma.'], FEARSOME('un Ogre in mischia'), ['Lancio Possente', 'Una Spinta Violenta su un nemico Barcollante lo scaglia entro Distanza Lunga: una Ferita e Prono.']], gear: 'Armatura leggera, martello a due mani, pistola' },
  { name: 'Ladro Halfling', group: 'Ogri, Halfling, Nani ed Elfi', type: 'Servitore', chars: '2 4 2 2 5 3 3 4', speed: 'Normale', res: 2, skills: 'Destrezza 4, Fascino 4, Furtività 5, Altro 3', attacks: ['Pugnale|Ravvicinata|2d/3|1|1|', 'Coltelli da Lancio|Corta|4d/3|2|1|'], prot: 'Furtività 3/5', abilities: [['Adesso Mi Vedi', 'Si oppone con Furtività agli attacchi che vede arrivare.'], ['Ladruncola Canaglia', 'Sparisce con Furtività anche senza copertura; muovendosi silenzioso può rubare con Destrezza contro Percezione.']], gear: 'Coltelli da lancio, pugnale, strumenti da ladro, borsello rubato (Argento)' },
  { name: 'Guardabirra Nano', group: 'Ogri, Halfling, Nani ed Elfi', type: 'Bruto', chars: '4 3 3 4 2 2 4 4', speed: 'Normale', res: 5, armoured: true, track: [['0 Ferite', '—'], ['1 Ferita', 'L’attaccante diventa Distratto'], ['2 Ferite', 'Sconfitto']], skills: 'Muscoli 4, Volontà 4, Altro 3', attacks: ['Martello da Guerra|Ravvicinata|4d/3|3|1|', 'Mani Nude|Ravvicinata|3d/4|-||infligge Barcollante'], prot: 'Atletica 2/3, Difesa 4/3', abilities: [['Una Mente Fredda Prevale', 'Come Azione, con Comando toglie Distratto a un personaggio per successo entro Distanza Media.']], gear: 'Armatura leggera, martello da guerra, set da gioco' },
  { name: 'Minatore Nano', group: 'Ogri, Halfling, Nani ed Elfi', type: 'Servitore', chars: '4 3 3 4 2 2 4 2', speed: 'Normale', res: 6, armoured: true, skills: 'Lavoro 4, Volontà 4, Altro 3', attacks: ['Piccone da Minatore|Ravvicinata|4d/3|4|2|', 'Carica Esplosiva|Corta – Media|3d/3|-||Pericolo (3) nella Zona (Tempra); se manca esplode nella sua'], prot: 'Atletica 1/3, Difesa 4/3', abilities: [['Rancori da Risolvere', 'Contro un nemico odiato è Distratto ma ha +1d in mischia contro di lui.'], ['Giù nel Buio', 'Ignora il Terreno Difficile sotterraneo; nessuno ha bonus di altezza contro di lui.']], gear: 'Armatura pesante, carica esplosiva, lanterna, piccone' },
  { name: 'Mercante Elfo', group: 'Ogri, Halfling, Nani ed Elfi', type: 'Bruto', chars: '4 4 3 3 4 4 4 4', speed: 'Normale', res: 4, armoured: true, track: [['0 Ferite', '—'], ['1 Ferita', 'Diventa Barcollante'], ['2 Ferite', 'Sconfitto']], skills: 'Destrezza 4, Fascino 4, Altro 3', attacks: ['Lama Ingioiellata|Ravvicinata|4d/3|3|1|'], prot: 'Atletica 4/3', abilities: [['Osso Duro', 'Contrattare con lui costa -1d.']], gear: 'Armatura leggera, spada, gemme (Oro)' },
  { name: 'Miliziano Elfo', group: 'Ogri, Halfling, Nani ed Elfi', type: 'Servitore', chars: '4 4 3 3 4 4 4 3', speed: 'Normale', res: 4, armoured: true, skills: 'Percezione 4, Tiro 4, Altro 3', attacks: ['Lancia|Corta|4d/3|4|2|', 'Arco Lungo|Media – Lunga|4d/4|4|2|'], prot: 'Atletica 4/3', abilities: [['Prodezza Marziale', '+1d a opporsi in mischia se un altro Miliziano libero è nella sua Zona.']], gear: 'Arco lungo, armatura leggera, lancia, uniforme' },
  // --------------------------------------------------------------- Bretonnia
  { name: 'Cavaliere della Cerca Bretonniano', group: 'Bretonnia', type: 'Campione', chars: '5 2 4 3 4 3 4 3', speed: 'Normale', res: 6, armoured: true, skills: 'Difesa 4, Mischia 4, Volontà 4, Altro 3', attacks: ['Spadone|Ravvicinata|4d/4|7|2|'], prot: 'Atletica 3/3, Difesa 5/4 scudo', abilities: [['Nobile Destriero', 'Su un cavallo bardato: +2 Resilienza, Veloce, le cariche riuscite gettano Prono.'], ['Grazia della Dama', 'Finché non ha agito nella battaglia, gli attacchi contro di lui sono Tetri.'], ['Virtuoso', 'Immune ad Atterrito e Distratto.']], gear: 'Armatura pesante, scudo, spadone' },
  { name: 'Scudiero Bretonniano', group: 'Bretonnia', type: 'Servitore', chars: '3 3 3 3 3 3 3 2', speed: 'Normale', res: 3, skills: 'Atletica 4, Percezione 4, Altro 3', attacks: ['Arco Lungo|Media – Lunga|3d/3|4|2|', 'Spada|Ravvicinata|3d/3|3|1|'], prot: 'Atletica 3/4', abilities: [['Nobile Servizio', '+2d per Aiutare il suo cavaliere.']], gear: 'Abiti da viaggio, arco lungo, spada' },
  // ------------------------------------------------------ Culti e cacciatori
  { name: 'Prete di Taal', group: 'Culti e preti', type: 'Campione', chars: '4 4 4 4 4 4 4 4', speed: 'Normale', res: 5, armoured: true, skills: 'Comando 4, Lancio 4, Sopravvivenza 4, Tiro 4, Volontà 4, Altro 3', attacks: ['Arco da Caccia|Media – Lunga|4d/4|3|2|', 'Giavellotto|Ravvicinata – Media|4d/4|3|1|'], prot: 'Atletica 4/3', abilities: [['Favore di Taal', 'Cacciare, seguire tracce e muoversi furtivo nella natura è Glorioso; ignora il Terreno Difficile della boscaglia.'], ['Avviluppare', 'Come Azione rende una Zona con vegetazione entro Distanza Lunga Terreno Difficile.']], gear: 'Arco, armatura leggera, giavellotto' },
  { name: 'Prete Guerriero di Ulric', group: 'Culti e preti', type: 'Campione', chars: '4 3 4 4 4 4 4 4', speed: 'Normale', res: 5, armoured: true, skills: 'Comando 4, Mischia 4, Muscoli 4, Tempra 4, Volontà 4, Altro 3', attacks: ['Ascia a Due Mani|Ravvicinata|3d/4|7|2|'], prot: 'Atletica 4/3', abilities: [['Favore di Ulric', 'Il freddo non lo penalizza; dopo una Ferita il prossimo attacco in mischia è Glorioso.'], ['Ululato di Battaglia', 'Dopo una Carica riuscita, gli alleati che ululano caricando in questo round hanno Prove Gloriose.']], gear: 'Armatura leggera, ascia a due mani' },
  { name: 'Cultista Sigmarita', group: 'Culti e preti', type: 'Servitore', chars: '3 3 3 3 3 3 3 3', speed: 'Normale', res: 3, skills: 'Furtività 3, Mischia 3, Percezione 3, Volontà 4, Altro 2', attacks: ['Martello da Guerra|Ravvicinata|3d/3|3|1|'], prot: 'Atletica 3/2', abilities: [['Torce e Forconi', 'Aiutando un alleato in mischia non serve una Prova: +1d, anche oltre il massimo.']], gear: 'Abiti da popolano, martello da guerra' },
  { name: 'Flagellante', group: 'Culti e preti', type: 'Bruto', chars: '3 2 3 3 3 3 3 2', speed: 'Normale', res: 3, track: [['0 Ferite', 'Può essere Ferito invece che Barcollante'], ['1 Ferita', 'Toglie una Ferita Recuperando'], ['2 Ferite', 'Sconfitto']], skills: 'Mischia 4, Tempra 5, Volontà 5, Altro 2', attacks: ['Flagello|Ravvicinata|3d/4|6|2|-2d se Barcollante', 'Ganci e Catene|Ravvicinata|3d/4|3|1|'], prot: 'Atletica 3/3', abilities: [['Imperituro', 'Immune ad Atterrito.'], ['Nessun Dolore', 'Quando diventerebbe Barcollante può subire invece una Ferita; Recuperando ne guarisce una.']], gear: 'Abiti da popolano, flagello' },
  { name: 'Cacciatore di Streghe', group: 'Culti e preti', type: 'Campione', chars: '4 4 4 4 5 4 4 4', speed: 'Normale', res: 5, armoured: true, skills: 'Mischia 4, Percezione 4, Tiro 4, Volontà 5, Altro 3', attacks: ['Spadone|Ravvicinata|3d/4|7|2|', 'Pistola|Ravvicinata – Corta|4d/4|5|1|ignora l’armatura, ricarica 3'], prot: 'Atletica 4/3', abilities: [['Emettere la Sentenza', 'Se non è Barcollante, chi ferisce tira +1d sulla tabella delle Ferite.'], ['Resistenza alla Magia', 'Gli incantesimi su di lui hanno Potenza -1.']] },
  { name: 'Prete di Sigmar', group: 'Culti e preti', type: 'Campione', chars: '4 3 4 4 4 4 4 4', speed: 'Normale', res: 6, armoured: true, skills: 'Comando 4, Mischia 4, Tempra 4, Volontà 5, Altro 3', attacks: ['Martello a Due Mani Sigmarita|Ravvicinata|3d/4|8|2|'], prot: 'Atletica 3/3', abilities: [['Favore di Sigmar', 'Una volta per scontro si toglie Barcollante senza Azione.'], ['Faro di Retta Virtù', 'Come Azione toglie Atterrito a sé e agli alleati vicini; con Volontà toglie Barcollante a uno per successo.']] },
  // ------------------------------------------------------- Streghe e stregoni
  { name: 'Astronomo di Corte', group: 'Streghe e stregoni', type: 'Campione', chars: '3 3 3 4 3 3 4 3', speed: 'Normale', res: 4, skills: 'Atletica 4, Comando 4, Memoria 4, Percezione 4, Volontà 4, Altro 3', attacks: ['Bastone da Mago|Ravvicinata|3d/3|3|1|', 'Mani Nude|Ravvicinata|3d/3|-||infligge Barcollante'], prot: 'Atletica 3/4', abilities: [MAGE(2)], mage: { level: 2, spells: [['Pugni Martellanti', 1, 'I suoi pugni contano come magici e infliggono F+Potenza Danni.'], ['Palla di Fuoco', 3, 'Bersaglio e vicini subiscono 5+Potenza Danni; i non-Mostruosità cadono Proni.'], ['Scudo di Quercia', 3, 'Lui e Potenza alleati vicini: +2 Resilienza (+1 se corazzati).']] } },
  { name: 'Strega Eremita', group: 'Streghe e stregoni', type: 'Campione', chars: '3 3 3 4 3 3 4 3', speed: 'Normale', res: 4, skills: 'Atletica 4, Destrezza 4, Furtività 4, Sopravvivenza 4, Volontà 4, Altro 3', attacks: ['Bastone da Strega|Ravvicinata|3d/3|3|1|'], prot: 'Atletica 3/4', abilities: [MAGE(2)], mage: { level: 2, spells: [['Manto Scintillante', 1, 'Vince i pareggi a difendersi, fallisce la Furtività.'], ['Rasoio Mentale', 2, '3+Potenza Danni che ignorano l’armatura; Volontà o Atterrito.'], ['Copia Illusoria', 3, 'Un suo doppio illusorio entro Distanza Lunga; Percezione con successi pari alla Potenza per smascherarlo.']] } },
  { name: 'Demonologo', group: 'Streghe e stregoni', type: 'Campione', chars: '3 3 3 4 3 3 4 3', speed: 'Normale', res: 4, skills: 'Atletica 4, Destrezza 4, Fascino 4, Memoria 4, Volontà 4, Altro 3', attacks: ['Pugnale Sacrificale|Ravvicinata|3d/3|3|1|'], prot: 'Atletica 3/4', abilities: [MAGE(2)], mage: { level: 2, spells: [['L’Evocazione', 1, '3+Potenza Danni a una creatura entro Distanza Lunga; se Arretra è Atterrita.'], ['Oscurità Crescente', 2, 'La prossima Prova di Potenza creature entro Distanza Media è Tetra.'], ['Recipiente Demoniaco', 3, 'Potenza creature nella sua Zona: prossimo attacco in mischia Glorioso, poi Barcollanti.']] } },
  { name: 'Necromante', group: 'Streghe e stregoni', type: 'Campione', chars: '3 3 3 4 3 3 4 3', speed: 'Normale', res: 4, skills: 'Atletica 4, Comando 4, Furtività 4, Memoria 4, Volontà 4, Altro 3', attacks: ['Falce|Ravvicinata|3d/3|5|2|'], prot: 'Atletica 3/4', abilities: [MAGE(2)], mage: { level: 2, spells: [['Invocazione di Nehek', 2, 'Potenza nonmorti entro Distanza Media guariscono una Ferita; rialza i Servitori nonmorti sconfitti.'], ['Danza Macabra di Vanhel', 2, 'Potenza nonmorti: +1 grado di Velocità e +1d in mischia.'], ['Abitanti del Sottosuolo', 3, 'Una Zona diventa Terreno Difficile e Pericolo pari alla Potenza.']] } },
  // ------------------------------------------------------ Animali e cavalcature
  { name: 'Rapace', group: 'Animali e cavalcature', type: 'Servitore', chars: '2 0 2 2 4 4 1 1', speed: 'Veloce', res: 2, skills: 'Atletica 3, Mischia 2, Percezione 4, Altro 1', attacks: ['Artigli Affilati|Ravvicinata|2d/2|2||'], prot: 'Atletica 4/3', abilities: [FLY, ['Alto nel Cielo', 'Di solito non agisce: vola fuori portata e avvisa il padrone dei nemici nascosti.']] },
  { name: 'Sciame di Ratti', group: 'Animali e cavalcature', type: 'Servitore', chars: '2 0 2 2 4 4 2 1', speed: 'Normale', res: null, skills: 'Atletica 2, Furtività 3, Mischia 3, Percezione 3, Sopravvivenza 3, Altro 1', attacks: ['Morso|Ravvicinata|3d/3|2||attacca tutti i nemici a Distanza Ravvicinata'], prot: 'Atletica 4/3', abilities: SWARM(5) },
  { name: 'Cane', group: 'Animali e cavalcature', type: 'Servitore', chars: '3 0 3 3 4 3 2 1', speed: 'Veloce', res: 3, skills: 'Atletica 3, Mischia 2, Percezione 3, Volontà 2, Altro 1', attacks: ['Morso|Ravvicinata|3d/2|3||'], prot: 'Atletica 3/3', abilities: [['Migliore Amico dell’Uomo', 'Resta col padrone e non è bersaglio; quando il padrone attacca con Mischia o Muscoli il cane blocca il nemico, che non può Arretrare.']] },
  { name: 'Cavallo', group: 'Animali e cavalcature', type: 'Servitore', chars: '3 0 3 3 3 4 2 1', speed: 'Veloce', res: 3, skills: 'Atletica 4, Mischia 3, Muscoli 4, Percezione 3, Tempra 3, Volontà 3, Altro 1', attacks: ['Zoccoli|Ravvicinata|3d/3|3||'], prot: 'Atletica 4/4', abilities: [['Nobile Destriero', 'Il cavaliere ottiene +1 Resilienza, diventa Veloce e le sue cariche riuscite gettano Prono.']] },
  { name: 'Lupo Gigante', group: 'Animali e cavalcature', type: 'Servitore', chars: '3 0 3 3 3 4 2 1', speed: 'Veloce', res: 3, skills: 'Atletica 4, Furtività 3, Mischia 3, Muscoli 3, Percezione 4, Tempra 3, Volontà 3, Altro 1', attacks: ['Fauci Serrate|Ravvicinata|3d/3|3||il bersaglio non può Arretrare'], prot: 'Atletica 4/4', abilities: [['Goblin Cavalcalupi', 'Il Goblin in sella ha +1 Resilienza, è Veloce e chi colpisce in mischia non può Arretrare.']] },
  { name: 'Lupo Bianco', group: 'Animali e cavalcature', type: 'Bruto', chars: '3 0 5 5 4 4 2 1', speed: 'Veloce', res: 5, track: [['0 Ferite', '—'], ['1 Ferita', 'Diventa Esausto'], ['2 Ferite', 'Sconfitto']], skills: 'Atletica 4, Furtività 3, Mischia 4, Muscoli 3, Percezione 4, Tempra 3, Volontà 4, Altro 1', attacks: ['Fauci Serrate|Ravvicinata|3d/4|5||il bersaglio non può Arretrare', 'Artigli Laceranti|Ravvicinata|3d/4|6||'], prot: 'Atletica 4/4', abilities: [['Immobilizza e Squarcia', 'Se le Fauci vanno a segno in Carica, attacca di nuovo con gli Artigli.'], FEARSOME('un Lupo Bianco')] },
  { name: 'Ragno Gigante', group: 'Animali e cavalcature', type: 'Servitore', chars: '3 0 3 3 4 4 2 1', speed: 'Veloce', res: 3, skills: 'Atletica 3, Furtività 3, Mischia 3, Percezione 3, Tempra 3, Volontà 3, Altro 1', attacks: ['Zanne Velenose|Ravvicinata|3d/3|-||infligge Esausto'], prot: 'Atletica 4/3', abilities: [['Rapidi Zampettii', 'Ignora il Terreno Difficile di foreste, rovine e pareti.'], ['Goblin Cavalcaragni', 'Il Goblin in sella ha +1 Resilienza, è Veloce e chi colpisce in mischia diventa Esausto.']] },
  { name: 'Cinghiale Gigante', group: 'Animali e cavalcature', type: 'Servitore', chars: '3 0 3 3 4 3 1 1', speed: 'Veloce', res: 5, armoured: true, skills: 'Atletica 3, Mischia 4, Muscoli 4, Percezione 3, Tempra 3, Volontà 4, Altro 1', attacks: ['Zanne Perforanti|Ravvicinata|3d/4|3||+1d e +1 Danno in Carica'], prot: 'Atletica 3/3', abilities: [['Orchi Cavalcacinghiali', 'L’Orco in sella ha +2 Resilienza, è Veloce e ha +1d e +1 Danno in Carica.']] },
  { name: 'Orso', group: 'Animali e cavalcature', type: 'Bruto', chars: '4 0 5 5 3 3 2 1', speed: 'Normale', res: 6, armoured: true, track: [['0 Ferite', '—'], ['1 Ferita', 'Diventa Esausto'], ['2 Ferite', 'Sconfitto']], skills: 'Atletica 3, Mischia 3, Muscoli 4, Percezione 3, Tempra 4, Volontà 4, Altro 1', attacks: ['Ampia Artigliata|Ravvicinata|4d/3|5||', 'Peso Schiacciante|Ravvicinata|3d/3|7||getta Prono prima che possa Arretrare'], prot: 'Atletica 3/3', abilities: [['Forza Duratura', 'Dopo un attacco riuscito può attaccare un altro nemico vicino.'], FEARSOME('un Orso')] },
  { name: 'Semigrifone', group: 'Animali e cavalcature', type: 'Bruto', chars: '4 0 5 4 4 4 2 1', speed: 'Veloce', res: 4, track: [['0 Ferite', '—'], ['1-2 Ferite', 'Diventa Esausto'], ['3 Ferite', 'Sconfitto']], skills: 'Atletica 3, Furtività 2, Mischia 4, Muscoli 4, Percezione 3, Tempra 3, Volontà 4, Altro 1', attacks: ['Perfidi Artigli|Ravvicinata|4d/4|5||'], prot: 'Atletica 4/3', abilities: [FEARSOME('un Semigrifone'), ['Cavalieri su Semigrifone', 'Il cavaliere Umano ha +2 Resilienza, è Veloce e Spaventoso; può attaccare anche con gli artigli, ma uno dei due attacchi è Tetro.']] },
  { name: 'Grande Cervo', group: 'Animali e cavalcature', type: 'Bruto', chars: '4 0 5 5 4 5 2 2', speed: 'Veloce', res: 5, track: [['0-1 Ferite', '—'], ['2 Ferite', 'Diventa Esausto'], ['3 Ferite', 'Sconfitto']], skills: 'Atletica 4, Furtività 3, Mischia 3, Muscoli 3, Percezione 4, Tempra 3, Volontà 3, Altro 1', attacks: ['Corna Possenti|Ravvicinata|4d/3|6||in Carica getta Prono', 'Travolgere|Ravvicinata|5d/3|5||solo contro nemici Proni'], prot: 'Atletica 5/4', abilities: [FEARSOME('un Grande Cervo'), ['Corona di Corna', 'Sceglie dove Arretrano i nemici; chi cade Prono può essere Travolto con una seconda Azione.']] },
  { name: 'Pegaso', group: 'Animali e cavalcature', type: 'Bruto', chars: '3 0 4 3 4 4 2 1', speed: 'Veloce', res: 3, track: [['0 Ferite', '—'], ['1 Ferita', 'Non può volare: atterra il prossimo turno'], ['2 Ferite', 'Sconfitto']], skills: 'Atletica 4, Mischia 3, Muscoli 3, Percezione 3, Tempra 3, Volontà 3, Altro 1', attacks: ['Zoccoli|Ravvicinata|3d/3|3||'], prot: 'Atletica 4/4', abilities: [FLY, ['Cavalieri su Pegaso', 'Il cavaliere ha +1 Resilienza, è Veloce, vola e le sue cariche gettano Prono.']] },
  // ------------------------------------------------------------- Uominibestia
  { name: 'Mastino da Guerra del Caos', group: 'Uominibestia', type: 'Servitore', chars: '4 0 3 3 3 4 2 1', speed: 'Veloce', res: 3, skills: 'Atletica 3, Furtività 4, Mischia 3, Percezione 4, Tempra 3, Volontà 3, Altro 1', attacks: ['Artigli Infilzanti|Ravvicinata|3d/3|3||il bersaglio non può Arretrare'], prot: 'Atletica 4/3', abilities: [FOREST] },
  { name: 'Nogor', group: 'Uominibestia', type: 'Servitore', chars: '3 3 3 3 3 4 2 2', speed: 'Normale', res: 4, armoured: true, skills: 'Destrezza 3, Furtività 4, Mischia 3, Tiro 3, Altro 2', attacks: ['Rozza Lancia|Ravvicinata – Corta|3d/3|3|1|', 'Arco Corto|Corta – Media|3d/3|3|2|'], prot: 'Atletica 4/2 scudo', abilities: [FOREST, ['Disprezzo Primordiale', '+1d agli attacchi contro i Barcollanti.']] },
  { name: 'Gor', group: 'Uominibestia', type: 'Servitore', chars: '4 2 3 4 3 4 2 2', speed: 'Normale', res: 5, armoured: true, skills: 'Furtività 4, Volontà 4, Altro 3', attacks: ['Asce Primitive|Ravvicinata|4d/3|3|1|+1 Danno usandone due'], prot: 'Atletica 4/3 scudo', abilities: [FOREST, ['Rabbia Primordiale', 'Da Barcollante ha +1d in mischia.']] },
  { name: 'Bestigor', group: 'Uominibestia', type: 'Bruto', chars: '4 3 4 4 4 4 3 3', speed: 'Normale', res: 6, armoured: true, track: [['0 Ferite', 'Non può scegliere di Arretrare o cadere Prono'], ['1 Ferita', 'Il prossimo attacco è Glorioso'], ['2 Ferite', 'Sconfitto']], skills: 'Mischia 4, Volontà 4, Altro 3', attacks: ['Ascia Gigante|Ravvicinata|3d/4|7|2|'], prot: 'Atletica 3/3, Difesa 4/3', abilities: [FOREST, ['Rabbia Sanguinaria', 'Attaccando può diventare Barcollante; da Barcollante ha +1d in mischia.']] },
  { name: 'Minotauro', group: 'Uominibestia', type: 'Bruto', chars: '4 3 5 5 3 4 2 2', speed: 'Normale', res: 6, armoured: true, track: [['0 Ferite', '—'], ['1 Ferita', '+1d in mischia per ogni Ferita'], ['2 Ferite', 'Sconfitto']], skills: 'Atletica 4, Comando 4, Mischia 5, Muscoli 4, Tempra 4, Volontà 4, Altro 2', attacks: ['Ascia|Ravvicinata|4d/5|5|1|+1 Danno usandone due', 'Ascia a Due Mani|Ravvicinata|3d/5|8|2|'], prot: 'Atletica 4/4', abilities: [['Divora i Caduti', 'Contro nemici Barcollanti, Proni o Feriti fa tirare +1d sulla tabella delle Ferite.'], FEARSOME('un Minotauro'), ['Carica Taurina', 'Come Azione travolge una Zona entro Distanza Media con Muscoli contro la miglior Difesa o Tempra: se vince tutti sono Barcollanti, se perde lo è lui.']] },
  { name: 'Drago Ogre', group: 'Uominibestia', type: 'Bruto', chars: '4 2 5 5 2 4 3 3', speed: 'Veloce', res: 8, armoured: true, track: [['0-1 Ferite', '—'], ['2-3 Ferite', 'Non può usare Artigli Affilati'], ['4 Ferite', 'Sconfitto']], skills: 'Atletica 5, Comando 4, Mischia 5, Muscoli 4, Tempra 4, Volontà 5, Altro 2', attacks: ['Uncini, Lame e Mazze|Ravvicinata|4d/5|7|2|', 'Artigli Affilati|Ravvicinata|4d/5|5||attacca tutti i nemici a Distanza Ravvicinata'], prot: 'Atletica 4/5', abilities: [FEARSOME('un Drago Ogre'), ['Tempesta Rinvigorente', 'Alla prima Carica i fulmini rendono Barcollante tutta la sua Zona e lui si riprende; si ricarica se ferito dalla magia.']] },
  { name: 'Centigor', group: 'Uominibestia', type: 'Bruto', chars: '4 3 4 4 2 4 2 2', speed: 'Veloce', res: 5, armoured: true, track: [['0 Ferite', '—'], ['1 Ferita', 'Cade Prono'], ['2 Ferite', 'Sconfitto']], skills: 'Atletica 3, Lancio 3, Mischia 4, Volontà 4, Altro 2', attacks: ['Lancia Seghettata|Corta|4d/4|4|1|+1d in Carica', 'Giavellotto|Corta – Media|3d/3|4|1|'], prot: 'Atletica 4/3 scudo', abilities: [FOREST, ['Ebbrezza Furiosa', 'Quando Carica, prima di attaccare rende Barcollanti tutti quelli a Distanza Ravvicinata.']] },
  { name: 'Sciamano Berciante', group: 'Uominibestia', type: 'Campione', chars: '4 3 3 4 3 4 4 4', speed: 'Normale', res: 4, skills: 'Atletica 4, Difesa 4, Furtività 4, Percezione 4, Volontà 4, Altro 3', attacks: ['Bastone Berciante|Ravvicinata|4d/3|5|2|'], prot: 'Atletica 4/4', abilities: [FOREST, ['Nato nella Magia', 'Mago di Livello 2: +1d alle Prove di Magia finché lui o un altro Mago vicino ha dadi nella Riserva degli Incidenti; si oppone alle Prove di Magia una volta per round.']], mage: { level: 2, spells: [['Manto di Ghorok', 1, 'Tutti nella sua Zona, lui compreso, diventano Barcollanti.'], ['Malaonda', 2, 'Insetti su una Zona entro Distanza Media: Potenza Danni che ignorano l’armatura.'], ['Devoluzione', 4, 'Una creatura entro Distanza Media con meno di Potenza successi in Volontà regredisce a una bestia fino all’alba.']] } },
  { name: 'Capobranco', group: 'Uominibestia', type: 'Campione', chars: '5 3 5 5 4 5 4 4', speed: 'Normale', res: 7, armoured: true, skills: 'Atletica 4, Comando 5, Furtività 4, Mischia 5, Volontà 5, Altro 3', attacks: ['Asce Brutali|Ravvicinata|5d/5|6|1|'], prot: 'Atletica 5/4', abilities: [FOREST, ['Strazia Nemici', 'Attaccando può diventare Barcollante; da Barcollante i suoi attacchi in mischia sono Gloriosi.'], ['Corno Berciante', 'Come Azione, con Comando sceglie un Uomobestia per successo: si muove subito, diventa Barcollante o si toglie Barcollante.']] },
  { name: 'Ecatombe', group: 'Uominibestia', type: 'Mostruosità', chars: '4 0 6 6 4 3 4 2', speed: 'Veloce', res: 7, armoured: true, track: [['0 Ferite', '—'], ['1-5 Ferite', 'Rigenerazione Mostruosa'], ['6 Ferite', 'Sconfitto']], skills: 'Atletica 4, Mischia 4, Muscoli 4, Percezione 4, Tempra 4, Volontà 4, Altro 2', attacks: ['Arti-Mannaia|Ravvicinata|4d/4|7||', 'Calpestare|Ravvicinata|6d/4|5||', 'Ingoiare per Intero|Ravvicinata|3d/4|-||chi non si oppone viene inghiottito: Pericolo (4) ogni turno finché non la ferisce dall’interno'], prot: 'Atletica 3/4, Difesa 4/2', abilities: [['Rigenerazione Mostruosa (Reazione)', 'A fine turno può guarire 1 Ferita diventando Barcollante; non le Ferite da fuoco.'], TERRIFYING('un’Ecatombe')] },
  // --------------------------------------------------------- Orchi e Goblin
  { name: 'Guerriero Goblin', group: 'Orchi e Goblin', type: 'Servitore', chars: '2 3 3 3 2 3 2 2', speed: 'Normale', res: 5, armoured: true, skills: 'Destrezza 3, Lancio 3, Mischia 3, Altro 2', attacks: ['Lancia Seghettata|Corta|2d/3|3|1|', 'Arco Corto|Corta – Media|3d/3|3|2|'], prot: 'Atletica 3/2 scudo', abilities: [HORDE('un Goblin'), ['Sporco Vigliacco', 'Se Barcollante subisce di nuovo Barcollante è sconfitto e scappa.']] },
  { name: 'Zubdolo', group: 'Orchi e Goblin', type: 'Servitore', chars: '4 3 3 3 4 3 3 2', speed: 'Normale', res: 4, armoured: true, skills: 'Difesa 4, Furtività 5, Mischia 4, Altro 3', attacks: ['Lunghi Coltelli|Ravvicinata|4d/4|3|1|'], prot: 'Atletica 3/3, Difesa 4/4', abilities: [['Minaccia Celata', 'In una Zona con almeno 5 Goblin sparisce con Furtività anche senza copertura.'], ['Pugnalata alla Zkiena', 'Contro chi non si oppone infligge +1 Danno per successo.']] },
  { name: 'Ragazzo Orco', group: 'Orchi e Goblin', type: 'Servitore', chars: '3 3 3 4 3 3 2 2', speed: 'Normale', res: 6, armoured: true, skills: 'Comando 4, Difesa 4, Mischia 4, Muscoli 4, Volontà 4, Altro 3', attacks: ['Coppia di Zpakka|Ravvicinata|3d/4|4|2|+1 Danno in Carica', 'Lancia Seghettata|Corta|3d/4|3|1|+1 Danno in Carica', 'Arco da Guerra|Media – Lunga|3d/3|3||'], prot: 'Atletica 3/3, Difesa 3/4 scudo', abilities: [['Potenza della Waaagh!', 'Aiutando un alleato in mischia non serve una Prova: gli dà un successo gratuito.']] },
  { name: 'Sciame di Sgorbi', group: 'Orchi e Goblin', type: 'Servitore', chars: '2 2 2 2 3 4 1 1', speed: 'Normale', res: null, skills: 'Atletica 2, Destrezza 3, Furtività 3, Lancio 3, Lavoro 3, Mischia 3, Altro 1', attacks: ['Assi e Martelli|Ravvicinata|3d/3|2|1|attacca tutti i nemici a Distanza Ravvicinata', 'Proiettili Assortiti|Corta – Media|2d/3|3|1|'], prot: 'Atletica 4/3', abilities: SWARM(6) },
  { name: 'Orco Ztrano', group: 'Orchi e Goblin', type: 'Campione', chars: '3 2 3 5 3 3 4 3', speed: 'Normale', res: 5, skills: 'Atletica 4, Comando 4, Mischia 4, Muscoli 4, Volontà 4, Altro 3', attacks: ['Zpakka e Bastone Adornato|Ravvicinata|3d/4|4|2|+1 Danno in Carica'], prot: 'Atletica 3/4', abilities: [['Prescelto di Gork', 'Mago di Livello 2: +1d alle Prove di Magia con almeno altri 3 Orchi nella Zona; si oppone alla magia una volta per round.']], mage: { level: 2, spells: [['Pugno di Gork', 1, '4+Potenza Danni a tutti i nemici a Distanza Ravvicinata.'], ['Zole Kattivo Zplende', 2, 'Potenza alleati hanno Potenza dadi bonus al prossimo attacco in mischia.'], ['Zguardo di Gork', 3, '4+Potenza Danni a chi vede in una Zona entro Distanza Media; poi è Barcollante.']] } },
  { name: 'Tizioztrambo', group: 'Orchi e Goblin', type: 'Campione', chars: '3 3 3 4 3 3 4 3', speed: 'Normale', res: 4, skills: 'Atletica 4, Comando 4, Destrezza 4, Furtività 4, Volontà 4, Altro 3', attacks: ['Bastone Adornato|Ravvicinata|3d/3|3|1|'], prot: 'Atletica 3/4', abilities: [['Prescelto di Mork', 'Mago di Livello 2: +1d alle Prove di Magia con almeno altri 5 Goblin nella Zona; si oppone alla magia una volta per round.']], mage: { level: 2, spells: [['Pugno di Mork', 1, '4+Potenza Danni a tutti i nemici a Distanza Ravvicinata.'], ['Luna Kattiva Zale', 2, 'Potenza nemici hanno -1d per Potenza alla prossima Prova per difendersi.'], ['Malokkio di Mork', 3, 'Un nemico è Distratto e perde Potenza Resilienza (non sotto la Resistenza) fino al prossimo Intermezzo.']] } },
  { name: 'Capo Orco', group: 'Orchi e Goblin', type: 'Campione', chars: '5 2 5 5 4 4 4 4', speed: 'Normale', res: 7, armoured: true, skills: 'Comando 5, Difesa 5, Mischia 5, Muscoli 5, Volontà 5, Altro 3', attacks: ['Coppia di Zpakka|Ravvicinata|5d/5|6|2|+1 Danno in Carica', 'Lancia Seghettata|Corta|5d/5|5|1|+1 Danno in Carica', 'Colpo Possente|Ravvicinata|5d/5|-||getta Prono'], prot: 'Atletica 4/3, Difesa 5/5 scudo', abilities: [['Carica Furiosa', 'Dopo un attacco in Carica può attaccare un altro nemico vicino.'], ['Waaagh!', 'Una volta per battaglia rende Glorioso un suo attacco e quelli di tutti gli Orchi nella sua Zona in quel turno.']] },
  { name: 'Capo Goblin', group: 'Orchi e Goblin', type: 'Campione', chars: '4 3 4 4 4 4 4 4', speed: 'Normale', res: 6, armoured: true, skills: 'Atletica 4, Comando 4, Mischia 5, Volontà 4, Altro 3', attacks: ['Ascia a Due Mani|Ravvicinata|3d/4|7|2|', 'Lancia Puntuta|Corta|4d/4|4|1|+1d in Carica'], prot: 'Atletica 4/4 scudo', abilities: [['Combatti Sporco', 'In superiorità numerica il suo attacco è Glorioso invece di +1d.'], ['Piano Astuto', 'Una volta per battaglia fa Arretrare i Goblin di una Zona, che poi agiscono liberamente.']] },
  // ----------------------------------------------------------------- Nonmorti
  { name: 'Scheletro Guerriero', group: 'Nonmorti', type: 'Servitore', chars: '2 2 3 3 2 2 1 1', speed: 'Lenta', res: 4, armoured: true, skills: 'Fascino 1, Mischia 3, Tiro 3, Altro 2', attacks: ['Lancia Arrugginita|Corta|2d/3|3|1|', 'Arco da Guerra|Media – Lunga|2d/3|3|2|'], prot: 'Atletica 2/2 scudo', abilities: [['Servitore Nonmorto', 'Immune agli effetti psicologici; non Arretra né cade Prono; un secondo Barcollante lo distrugge.'], FEARSOME('uno Scheletro in mischia'), HORDE('uno Scheletro')] },
  { name: 'Guardia Wight', group: 'Nonmorti', type: 'Bruto', chars: '3 3 4 4 2 2 2 2', speed: 'Lenta', res: 6, armoured: true, track: [['0 Ferite', '—'], ['1 Ferita', '—'], ['2 Ferite', 'Sconfitto']], skills: 'Fascino 1, Difesa 4, Mischia 4, Altro 3', attacks: ['Falce da Guerra|Ravvicinata|3d/4|6|2|', 'Khopesh|Ravvicinata|3d/4|5|1|'], prot: 'Atletica 2/3, Difesa 3/4 scudo', abilities: [['Signore della Guerra Nonmorto', 'Immune agli effetti psicologici; non Arretra né cade Prono; un secondo Barcollante gli infligge una Ferita.'], FEARSOME('un Wight in mischia'), ['Colpo Devastante', 'Ogni attacco riuscito riduce di 1 la Resilienza del bersaglio fino al prossimo Intermezzo.']] },
  { name: 'Vampiro', group: 'Nonmorti', type: 'Campione', chars: '6 4 5 5 5 5 5 5', speed: 'Normale', res: 5, skills: 'Atletica 5, Comando 5, Difesa 5, Mischia 5, Altro 4', attacks: ['Lama Affilata|Ravvicinata|6d/5|6|1|', 'Zanne|Ravvicinata|5d/4|4||se ferisce, il Vampiro guarisce una Ferita'], prot: 'Atletica 5/5, Difesa 6/5', abilities: [['Maledizione di Lahmia', 'Immune agli effetti psicologici; la luce del sole è un Pericolo (2) che lo incendia; fuoco, argento, armi benedette e aglio contano come Pericoli.'], FEARSOME('un Vampiro in mischia'), ['Arti Oscure', 'Mago di Livello 2: ferendo coi denti ha +1d alla prossima Prova di Magia.']], mage: { level: 2, spells: [['Padrone Oscuro della Notte', 1, 'Per Potenza turni ignora una delle sue debolezze.'], ['Invocazione di Nehek', 2, 'Potenza nonmorti guariscono una Ferita o si rialzano.'], ['Danza Macabra di Vanhel', 2, 'Potenza nonmorti: +1 grado di Velocità e +1d in mischia.']] } },
  { name: 'Sacerdote Liche', group: 'Nonmorti', type: 'Campione', chars: '3 3 3 4 2 3 4 2', speed: 'Normale', res: 4, skills: 'Atletica 4, Comando 4, Destrezza 4, Memoria 4, Volontà 4, Altro 3', attacks: ['Khopesh|Ravvicinata|3d/3|4|1|'], prot: 'Atletica 3/4', abilities: [['Immortale Nehekhariano', 'Immune agli effetti psicologici; tira -1d sulla tabella delle Ferite (minimo 1d).'], FEARSOME('un Liche in mischia'), ['Cultista Funebre', 'Mago di Livello 2: +1d alle Prove di Magia se non si muove.']], mage: { level: 2, spells: [['Sorgi!', 2, 'Potenza nonmorti guariscono una Ferita o si rialzano.'], ['Lame Maledette di Djaf', 2, 'I nonmorti in una Zona hanno +1d in mischia per Potenza turni.'], ['Essiccamento di Usekhp', 2, 'Potenza creature sono Esauste per Potenza turni.']] } },
  { name: 'Re dei Sepolcri', group: 'Nonmorti', type: 'Campione', chars: '5 3 5 6 3 3 4 4', speed: 'Normale', res: 7, armoured: true, skills: 'Comando 5, Mischia 5, Tempra 5, Volontà 5, Altro 4', attacks: ['Khopesh|Ravvicinata|5d/5|6|1|'], prot: 'Atletica 3/4, Difesa 5/4', abilities: [['Immortale Nehekhariano', 'Immune agli effetti psicologici; tira -1d sulla tabella delle Ferite (minimo 1d).'], FEARSOME('un Re dei Sepolcri in mischia'), ['Sia Fatto il Mio Volere', 'Servitori e Bruti nonmorti entro Distanza Corta hanno +1d ad attaccare e difendersi in mischia.'], ['Maledizione della Necropoli', 'Chi lo sconfigge affronta un Pericolo (3) di Volontà.']] },
  { name: 'Drago d’Ossa Necrolith', group: 'Nonmorti', type: 'Mostruosità', chars: '4 0 6 6 2 4 2 1', speed: 'Veloce', res: 9, armoured: true, track: [['0-2 Ferite', '—'], ['3-4 Ferite', 'Non può volare: atterra il prossimo turno'], ['5 Ferite', 'Sconfitto']], skills: 'Atletica 4, Mischia 5, Muscoli 4, Percezione 3, Tempra 4, Volontà 3, Altro 1', attacks: ['Artigli Malefici|Ravvicinata|4d/5|7||getta Prono prima che possa Arretrare', 'Calpestare|Ravvicinata|6d/4|5||'], prot: 'Atletica 4/4', abilities: [['Mostruosità Nonmorta (Reazione)', 'Immune agli effetti psicologici; la Reazione gli infligge una Ferita (con un Liche o Re in sella può invece Arretrare o cadere Prono).'], FLY, TERRIFYING('un Drago d’Ossa'), ['Soffio di Essiccamento', 'Come Azione, se non è Barcollante: Pericolo (3) di Volontà a una Zona entro Distanza Media.']] },
  // --------------------------------------------------------------- Mostri
  { name: 'Grifone', group: 'Mostri', type: 'Mostruosità', chars: '5 0 6 5 4 4 2 1', speed: 'Veloce', res: 7, armoured: true, track: [['0-1 Ferite', '—'], ['2-3 Ferite', 'Non può volare: atterra il prossimo turno'], ['4 Ferite', 'Sconfitto']], skills: 'Atletica 4, Mischia 4, Muscoli 4, Percezione 4, Tempra 3, Volontà 4, Altro 1', attacks: ['Perfidi Artigli|Ravvicinata|5d/4|7||getta Prono prima che possa Arretrare', 'Fauci Seghettate|Ravvicinata|5d/4|6||solo contro nemici Proni', 'Calpestare|Ravvicinata|6d/4|5||'], prot: 'Atletica 4/4', abilities: [MONSTER_FLY, TERRIFYING('un Grifone')] },
  { name: 'Drago della Foresta', group: 'Mostri', type: 'Mostruosità', chars: '6 0 7 6 4 4 3 2', speed: 'Veloce', res: 9, armoured: true, track: [['0-2 Ferite', '—'], ['3-5 Ferite', 'Non può volare: atterra il prossimo turno'], ['6 Ferite', 'Sconfitto']], skills: 'Atletica 4, Mischia 5, Muscoli 4, Volontà 4, Altro 3', attacks: ['Perfidi Artigli|Ravvicinata|6d/5|8||', 'Fauci Zannute|Ravvicinata|6d/5|7||infligge Esausto', 'Calpestare|Ravvicinata|7d/4|6||contro chi non è bersaglio di altri suoi attacchi'], prot: 'Atletica 4/4', abilities: [MONSTER_FLY, TERRIFYING('un Drago'), ['Soffio Soporifero', 'Come Azione, se non è Barcollante: Pericolo (2) di Tempra a una Zona entro Distanza Media che rende Esausti (o Indifesi chi lo è già).']] },
  { name: 'Viverna', group: 'Mostri', type: 'Mostruosità', chars: '5 0 6 6 3 4 1 1', speed: 'Veloce', res: 8, armoured: true, track: [['0-2 Ferite', '—'], ['3 Ferite', 'Non può volare: atterra il prossimo turno'], ['4 Ferite', 'Sconfitto']], skills: 'Atletica 3, Mischia 5, Muscoli 4, Percezione 3, Tempra 3, Volontà 3, Altro 1', attacks: ['Morso Rancido|Ravvicinata|5d/5|7||', 'Coda Velenosa|Ravvicinata|6d/4|6||infligge Esausto'], prot: 'Atletica 4/3', abilities: [MONSTER_FLY, TERRIFYING('una Viverna'), ['Fetore Nauseante', 'Quando entra nella Zona dei nemici, questi lasciano ciò che hanno in mano o diventano Distratti.']] },
  { name: 'Troll', group: 'Mostri', type: 'Bruto', chars: '3 1 5 4 2 3 1 1', speed: 'Normale', res: 5, armoured: true, track: [['0 Ferite', '—'], ['1-2 Ferite', 'Rigenerazione'], ['3 Ferite', 'Sconfitto']], skills: 'Atletica 3, Mischia 4, Muscoli 4, Percezione 2, Tempra 4, Volontà 2, Altro 1', attacks: ['Grande Clava|Ravvicinata|3d/4|6|1|'], prot: 'Atletica 3/3', abilities: [['Stupidità', 'È sempre Distratto (-1d); se ferito o guidato con Comando da un alleato smette fino a fine battaglia.'], FEARSOME('un Troll'), ['Rigenerazione', 'A fine turno, se non è Barcollante, può diventarlo per guarire 1 Ferita (non da fuoco).'], ['Vomito', 'Come Azione, Pericolo (3) di Tempra a un nemico Barcollante vicino.']] },
  { name: 'Megera Troll', group: 'Mostri', type: 'Mostruosità', chars: '2 2 6 6 2 3 3 2', speed: 'Normale', res: 8, armoured: true, track: [['0 Ferite', '+1d alle Prove di Magia'], ['1-5 Ferite', 'Rigenerazione'], ['6 Ferite', 'Sconfitto']], skills: 'Atletica 3, Comando 4, Lancio 4, Mischia 4, Muscoli 4, Percezione 3, Tempra 4, Volontà 5, Altro 2', attacks: ['Ceppo Nodoso|Ravvicinata|2d/4|7|1|', 'Grande Rete|Ravvicinata – Corta|2d/4|-|1|infligge Ostacolato', 'Abbraccio Asfissiante|Ravvicinata|6d/4|5||il bersaglio non può Arretrare'], prot: 'Atletica 3/3', abilities: [TERRIFYING('una Megera Troll'), ['Rigenerazione Mostruosa (Reazione)', 'A fine turno guarisce 1 Ferita diventando Barcollante (non da fuoco).'], ['Alito Paludoso', 'Come Azione, se non è Barcollante: Pericolo (3) di Tempra a una Zona entro Distanza Media.'], ['Mamma ha Sempre Ragione', 'Maga di Livello 2: senza Ferite ha +1d alle Prove di Magia.']], mage: { level: 2, spells: [['Zveglia!', 1, 'Potenza alleati perdono Distratto.'], ['Cervello di Troll', 2, 'Potenza nemici sono Distratti per Potenza turni.'], ['Vortice Fetido', 3, 'Una Zona e le adiacenti diventano Terreno Difficile: chi non fa Potenza successi in Atletica cade Prono e viene trascinato.']] } },
  { name: 'Gigante', group: 'Mostri', type: 'Mostruosità', chars: '3 1 6 6 2 3 2 1', speed: 'Normale', res: 7, armoured: true, track: [['0-2 Ferite', '—'], ['3-5 Ferite', 'Non può usare Calpestare'], ['6 Ferite', 'Sconfitto']], skills: 'Atletica 3, Mischia 3, Muscoli 5, Percezione 2, Tempra 5, Volontà 4, Altro 1', attacks: ['Testata|Ravvicinata|6d/5|8||+1d sulla tabella delle Ferite (d10 1-2)', 'Divora|Ravvicinata|2d/3|-||inghiotte il bersaglio: Pericolo (4) ogni turno (d10 3-4)', 'Vattene Via!|Ravvicinata|6d/5|-||scaglia il bersaglio entro Distanza Lunga: una Ferita e Prono (d10 5-6)', 'Colpo di Clava|Ravvicinata|3d/3|7||colpisce tutti i nemici vicini (d10 7-8)', 'Calpestare|Ravvicinata|6d/5|5||'], prot: 'Atletica 3/3', abilities: [['Attacchi del Gigante', 'Ogni attacco: tira 1d10 per scegliere (1-2 Testata, 3-4 Divora, 5-6 Vattene Via!, 7-8 Colpo di Clava, 9-10 Salta Su e Giù: Pericolo (3) di Tempra ai vicini).'], ['Instabile (Reazione)', 'La Reazione lo fa cadere Prono: chi è nella sua Zona affronta un Pericolo (3) di Atletica.'], TERRIFYING('un Gigante')] },
  { name: 'Spirito del Bosco Selvaggio', group: 'Mostri', type: 'Campione', chars: '5 4 4 4 5 5 3 4', speed: 'Normale', res: 5, armoured: true, skills: 'Atletica 4, Fascino 4, Mischia 4, Tempra 4, Volontà 4, Altro 3', attacks: ['Artigli di Alburno|Ravvicinata|5d/4|5||'], prot: 'Atletica 5/4', abilities: [['Spirito della Foresta', 'Nei boschi ignora il Terreno Difficile.'], FEARSOME('uno Spirito del Bosco Selvaggio'), ['Spirito Oscuro', 'Contro un nemico Atterrito ha +1d e fa tirare +1d sulla tabella delle Ferite.'], ['Mutaforma', 'Può assumere l’aspetto di qualunque umanoide; Percezione (di solito Tetra) per intravederne la natura.']] },
  { name: 'Versipelle', group: 'Mostri', type: 'Bruto', chars: '5 0 4 4 4 4 2 1', speed: 'Veloce', res: 5, armoured: true, track: [['0 Ferite', '—'], ['1-2 Ferite', 'Forma Mutata'], ['3 Ferite', 'Sconfitto']], skills: 'Atletica 3, Furtività 3, Mischia 3, Muscoli 3, Percezione 3, Tempra 3, Volontà 3, Altro 1', attacks: ['Zanne e Artigli|Ravvicinata|5d/3|5||'], prot: 'Atletica 4/3', abilities: [['Rabbia Sanguinaria', 'Attaccando può diventare Barcollante; da Barcollante ha +1d in mischia.'], ['Forma Mutata', 'A fine turno, se non è Barcollante, può diventarlo per guarire una Ferita (non da fuoco) e rendere Barcollanti tutti i vicini.']] },
];

export const NPCS: Npc[] = DEFS.map(npc);
export const NPC_GROUPS = [...new Set(NPCS.map((n) => n.group))];
export const getNpc = (id: string | null | undefined): Npc | undefined => NPCS.find((n) => n.id === id);

/** What the host needs to settle attacks against this creature (null for swarms). */
export function npcPool(n: Npc) {
  if (n.resilience === null) return null;
  const score = (p: NpcProtection) => p.dice * p.target;
  const best = [...n.protection].sort((a, b) => score(b) - score(a))[0] ?? { skill: 'Atletica', dice: n.chars.ag, target: n.skills.atletica ?? n.other };
  // shots: only a shield lets Difesa stop them
  const ranged = n.protection.filter((p) => p.skill !== 'Difesa' || p.shield).sort((a, b) => score(b) - score(a))[0] ?? best;
  return {
    type: n.type,
    resilience: n.resilience,
    toughness: n.chars.r,
    armoured: n.armoured,
    melee: { dice: best.dice, target: best.target },
    ranged: { dice: ranged.dice, target: ranged.target },
    wounds: 0,
    maxWounds: n.maxWounds,
    track: n.track,
    monster: n.type === 'Mostruosità' || undefined,
  };
}
